// Copyright (c) 2005-2023 Code Synthesis.
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis gives permission
// to link this program with the Xerces-C++ library (or with modified
// versions of Xerces-C++ that use the same license as Xerces-C++), and
// distribute linked combinations including the two. You must obey the GNU
// General Public License version 2 in all respects for all of the code
// used other than Xerces-C++. If you modify this copy of the program, you
// may extend this exception to your version of the program, but you are
// not obligated to do so. If you do not wish to do so, delete this
// exception statement from your version.
//
// Furthermore, Code Synthesis makes a special exception for the Free/Libre
// and Open Source Software (FLOSS) which is described in the accompanying
// FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "Auxiliary.hxx"

namespace xsd
{
  namespace qif30
  {
    // CoordinateSystemSetType
    //

    const CoordinateSystemSetType::CoordinateSystem_sequence& CoordinateSystemSetType::
    CoordinateSystem () const
    {
      return this->CoordinateSystem_;
    }

    CoordinateSystemSetType::CoordinateSystem_sequence& CoordinateSystemSetType::
    CoordinateSystem ()
    {
      return this->CoordinateSystem_;
    }

    void CoordinateSystemSetType::
    CoordinateSystem (const CoordinateSystem_sequence& s)
    {
      this->CoordinateSystem_ = s;
    }

    const CoordinateSystemSetType::n_type& CoordinateSystemSetType::
    n () const
    {
      return this->n_.get ();
    }

    CoordinateSystemSetType::n_type& CoordinateSystemSetType::
    n ()
    {
      return this->n_.get ();
    }

    void CoordinateSystemSetType::
    n (const n_type& x)
    {
      this->n_.set (x);
    }

    void CoordinateSystemSetType::
    n (::std::unique_ptr< n_type > x)
    {
      this->n_.set (std::move (x));
    }


    // CADCoordinateSystemType
    //

    const CADCoordinateSystemType::CoordinateSystemCore_type& CADCoordinateSystemType::
    CoordinateSystemCore () const
    {
      return this->CoordinateSystemCore_.get ();
    }

    CADCoordinateSystemType::CoordinateSystemCore_type& CADCoordinateSystemType::
    CoordinateSystemCore ()
    {
      return this->CoordinateSystemCore_.get ();
    }

    void CADCoordinateSystemType::
    CoordinateSystemCore (const CoordinateSystemCore_type& x)
    {
      this->CoordinateSystemCore_.set (x);
    }

    void CADCoordinateSystemType::
    CoordinateSystemCore (::std::unique_ptr< CoordinateSystemCore_type > x)
    {
      this->CoordinateSystemCore_.set (std::move (x));
    }


    // AuxiliarySetType
    //

    const AuxiliarySetType::Auxiliary_sequence& AuxiliarySetType::
    Auxiliary () const
    {
      return this->Auxiliary_;
    }

    AuxiliarySetType::Auxiliary_sequence& AuxiliarySetType::
    Auxiliary ()
    {
      return this->Auxiliary_;
    }

    void AuxiliarySetType::
    Auxiliary (const Auxiliary_sequence& s)
    {
      this->Auxiliary_ = s;
    }

    const AuxiliarySetType::n_type& AuxiliarySetType::
    n () const
    {
      return this->n_.get ();
    }

    AuxiliarySetType::n_type& AuxiliarySetType::
    n ()
    {
      return this->n_.get ();
    }

    void AuxiliarySetType::
    n (const n_type& x)
    {
      this->n_.set (x);
    }

    void AuxiliarySetType::
    n (::std::unique_ptr< n_type > x)
    {
      this->n_.set (std::move (x));
    }


    // AuxiliaryBaseType
    //


    // PointAuxiliaryType
    //

    const PointAuxiliaryType::XYZ_type& PointAuxiliaryType::
    XYZ () const
    {
      return this->XYZ_.get ();
    }

    PointAuxiliaryType::XYZ_type& PointAuxiliaryType::
    XYZ ()
    {
      return this->XYZ_.get ();
    }

    void PointAuxiliaryType::
    XYZ (const XYZ_type& x)
    {
      this->XYZ_.set (x);
    }

    void PointAuxiliaryType::
    XYZ (::std::unique_ptr< XYZ_type > x)
    {
      this->XYZ_.set (std::move (x));
    }


    // LineAuxiliaryType
    //

    const LineAuxiliaryType::StartPoint_type& LineAuxiliaryType::
    StartPoint () const
    {
      return this->StartPoint_.get ();
    }

    LineAuxiliaryType::StartPoint_type& LineAuxiliaryType::
    StartPoint ()
    {
      return this->StartPoint_.get ();
    }

    void LineAuxiliaryType::
    StartPoint (const StartPoint_type& x)
    {
      this->StartPoint_.set (x);
    }

    void LineAuxiliaryType::
    StartPoint (::std::unique_ptr< StartPoint_type > x)
    {
      this->StartPoint_.set (std::move (x));
    }

    const LineAuxiliaryType::EndPoint_type& LineAuxiliaryType::
    EndPoint () const
    {
      return this->EndPoint_.get ();
    }

    LineAuxiliaryType::EndPoint_type& LineAuxiliaryType::
    EndPoint ()
    {
      return this->EndPoint_.get ();
    }

    void LineAuxiliaryType::
    EndPoint (const EndPoint_type& x)
    {
      this->EndPoint_.set (x);
    }

    void LineAuxiliaryType::
    EndPoint (::std::unique_ptr< EndPoint_type > x)
    {
      this->EndPoint_.set (std::move (x));
    }

    const LineAuxiliaryType::LineStyle_optional& LineAuxiliaryType::
    LineStyle () const
    {
      return this->LineStyle_;
    }

    LineAuxiliaryType::LineStyle_optional& LineAuxiliaryType::
    LineStyle ()
    {
      return this->LineStyle_;
    }

    void LineAuxiliaryType::
    LineStyle (const LineStyle_type& x)
    {
      this->LineStyle_.set (x);
    }

    void LineAuxiliaryType::
    LineStyle (const LineStyle_optional& x)
    {
      this->LineStyle_ = x;
    }

    void LineAuxiliaryType::
    LineStyle (::std::unique_ptr< LineStyle_type > x)
    {
      this->LineStyle_.set (std::move (x));
    }


    // AuxiliaryPlaneBaseType
    //

    const AuxiliaryPlaneBaseType::Plane_type& AuxiliaryPlaneBaseType::
    Plane () const
    {
      return this->Plane_.get ();
    }

    AuxiliaryPlaneBaseType::Plane_type& AuxiliaryPlaneBaseType::
    Plane ()
    {
      return this->Plane_.get ();
    }

    void AuxiliaryPlaneBaseType::
    Plane (const Plane_type& x)
    {
      this->Plane_.set (x);
    }

    void AuxiliaryPlaneBaseType::
    Plane (::std::unique_ptr< Plane_type > x)
    {
      this->Plane_.set (std::move (x));
    }


    // PlaneReferenceType
    //
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

#include <xsd/cxx/tree/type-factory-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_factory_plate< 0, wchar_t >
  type_factory_plate_init;
}

namespace xsd
{
  namespace qif30
  {
    // CoordinateSystemSetType
    //

    CoordinateSystemSetType::
    CoordinateSystemSetType ()
    : ::xml_schema::type (),
      CoordinateSystem_ (this),
      n_ (this)
    {
    }

    CoordinateSystemSetType::
    CoordinateSystemSetType (const n_type& n)
    : ::xml_schema::type (),
      CoordinateSystem_ (this),
      n_ (n, this)
    {
    }

    CoordinateSystemSetType::
    CoordinateSystemSetType (const CoordinateSystemSetType& x,
                             ::xml_schema::flags f,
                             ::xml_schema::container* c)
    : ::xml_schema::type (x, f, c),
      CoordinateSystem_ (x.CoordinateSystem_, f, this),
      n_ (x.n_, f, this)
    {
    }

    CoordinateSystemSetType::
    CoordinateSystemSetType (const xercesc::DOMElement& e,
                             ::xml_schema::flags f,
                             ::xml_schema::container* c)
    : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
      CoordinateSystem_ (this),
      n_ (this)
    {
      if ((f & ::xml_schema::flags::base) == 0)
      {
        ::xsd::cxx::xml::dom::parser< wchar_t > p (e, true, false, true);
        this->parse (p, f);
      }
    }

    void CoordinateSystemSetType::
    parse (::xsd::cxx::xml::dom::parser< wchar_t >& p,
           ::xml_schema::flags f)
    {
      for (; p.more_content (); p.next_content (false))
      {
        const xercesc::DOMElement& i (p.cur_element ());
        const ::xsd::cxx::xml::qualified_name< wchar_t > n (
          ::xsd::cxx::xml::dom::name< wchar_t > (i));

        // CoordinateSystem
        //
        if (n.name () == L"CoordinateSystem" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< CoordinateSystem_type > r (
            CoordinateSystem_traits::create (i, f, this));

          this->CoordinateSystem_.push_back (::std::move (r));
          continue;
        }

        break;
      }

      while (p.more_attributes ())
      {
        const xercesc::DOMAttr& i (p.next_attribute ());
        const ::xsd::cxx::xml::qualified_name< wchar_t > n (
          ::xsd::cxx::xml::dom::name< wchar_t > (i));

        if (n.name () == L"n" && n.namespace_ ().empty ())
        {
          this->n_.set (n_traits::create (i, f, this));
          continue;
        }
      }

      if (!n_.present ())
      {
        throw ::xsd::cxx::tree::expected_attribute< wchar_t > (
          L"n",
          L"");
      }
    }

    CoordinateSystemSetType* CoordinateSystemSetType::
    _clone (::xml_schema::flags f,
            ::xml_schema::container* c) const
    {
      return new class CoordinateSystemSetType (*this, f, c);
    }

    CoordinateSystemSetType& CoordinateSystemSetType::
    operator= (const CoordinateSystemSetType& x)
    {
      if (this != &x)
      {
        static_cast< ::xml_schema::type& > (*this) = x;
        this->CoordinateSystem_ = x.CoordinateSystem_;
        this->n_ = x.n_;
      }

      return *this;
    }

    CoordinateSystemSetType::
    ~CoordinateSystemSetType ()
    {
    }

    // CADCoordinateSystemType
    //

    CADCoordinateSystemType::
    CADCoordinateSystemType ()
    : ::xsd::qif30::DrawableBaseType (),
      CoordinateSystemCore_ (this)
    {
    }

    CADCoordinateSystemType::
    CADCoordinateSystemType (const id_type& id,
                             const CoordinateSystemCore_type& CoordinateSystemCore)
    : ::xsd::qif30::DrawableBaseType (id),
      CoordinateSystemCore_ (CoordinateSystemCore, this)
    {
    }

    CADCoordinateSystemType::
    CADCoordinateSystemType (const id_type& id,
                             ::std::unique_ptr< CoordinateSystemCore_type > CoordinateSystemCore)
    : ::xsd::qif30::DrawableBaseType (id),
      CoordinateSystemCore_ (std::move (CoordinateSystemCore), this)
    {
    }

    CADCoordinateSystemType::
    CADCoordinateSystemType (const CADCoordinateSystemType& x,
                             ::xml_schema::flags f,
                             ::xml_schema::container* c)
    : ::xsd::qif30::DrawableBaseType (x, f, c),
      CoordinateSystemCore_ (x.CoordinateSystemCore_, f, this)
    {
    }

    CADCoordinateSystemType::
    CADCoordinateSystemType (const xercesc::DOMElement& e,
                             ::xml_schema::flags f,
                             ::xml_schema::container* c)
    : ::xsd::qif30::DrawableBaseType (e, f | ::xml_schema::flags::base, c),
      CoordinateSystemCore_ (this)
    {
      if ((f & ::xml_schema::flags::base) == 0)
      {
        ::xsd::cxx::xml::dom::parser< wchar_t > p (e, true, false, true);
        this->parse (p, f);
      }
    }

    void CADCoordinateSystemType::
    parse (::xsd::cxx::xml::dom::parser< wchar_t >& p,
           ::xml_schema::flags f)
    {
      this->::xsd::qif30::DrawableBaseType::parse (p, f);

      for (; p.more_content (); p.next_content (false))
      {
        const xercesc::DOMElement& i (p.cur_element ());
        const ::xsd::cxx::xml::qualified_name< wchar_t > n (
          ::xsd::cxx::xml::dom::name< wchar_t > (i));

        // CoordinateSystemCore
        //
        if (n.name () == L"CoordinateSystemCore" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< CoordinateSystemCore_type > r (
            CoordinateSystemCore_traits::create (i, f, this));

          if (!CoordinateSystemCore_.present ())
          {
            this->CoordinateSystemCore_.set (::std::move (r));
            continue;
          }
        }

        break;
      }

      if (!CoordinateSystemCore_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< wchar_t > (
          L"CoordinateSystemCore",
          L"http://qifstandards.org/xsd/qif3");
      }
    }

    CADCoordinateSystemType* CADCoordinateSystemType::
    _clone (::xml_schema::flags f,
            ::xml_schema::container* c) const
    {
      return new class CADCoordinateSystemType (*this, f, c);
    }

    CADCoordinateSystemType& CADCoordinateSystemType::
    operator= (const CADCoordinateSystemType& x)
    {
      if (this != &x)
      {
        static_cast< ::xsd::qif30::DrawableBaseType& > (*this) = x;
        this->CoordinateSystemCore_ = x.CoordinateSystemCore_;
      }

      return *this;
    }

    CADCoordinateSystemType::
    ~CADCoordinateSystemType ()
    {
    }

    // AuxiliarySetType
    //

    AuxiliarySetType::
    AuxiliarySetType ()
    : ::xml_schema::type (),
      Auxiliary_ (this),
      n_ (this)
    {
    }

    AuxiliarySetType::
    AuxiliarySetType (const n_type& n)
    : ::xml_schema::type (),
      Auxiliary_ (this),
      n_ (n, this)
    {
    }

    AuxiliarySetType::
    AuxiliarySetType (const AuxiliarySetType& x,
                      ::xml_schema::flags f,
                      ::xml_schema::container* c)
    : ::xml_schema::type (x, f, c),
      Auxiliary_ (x.Auxiliary_, f, this),
      n_ (x.n_, f, this)
    {
    }

    AuxiliarySetType::
    AuxiliarySetType (const xercesc::DOMElement& e,
                      ::xml_schema::flags f,
                      ::xml_schema::container* c)
    : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
      Auxiliary_ (this),
      n_ (this)
    {
      if ((f & ::xml_schema::flags::base) == 0)
      {
        ::xsd::cxx::xml::dom::parser< wchar_t > p (e, true, false, true);
        this->parse (p, f);
      }
    }

    void AuxiliarySetType::
    parse (::xsd::cxx::xml::dom::parser< wchar_t >& p,
           ::xml_schema::flags f)
    {
      for (; p.more_content (); p.next_content (false))
      {
        const xercesc::DOMElement& i (p.cur_element ());
        const ::xsd::cxx::xml::qualified_name< wchar_t > n (
          ::xsd::cxx::xml::dom::name< wchar_t > (i));

        // Auxiliary
        //
        {
          ::std::unique_ptr< ::xsd::cxx::tree::type > tmp (
            ::xsd::cxx::tree::type_factory_map_instance< 0, wchar_t > ().create (
              L"Auxiliary",
              L"http://qifstandards.org/xsd/qif3",
              0,
              true, true, i, n, f, this));

          if (tmp.get () != 0)
          {
            ::std::unique_ptr< Auxiliary_type > r (
              dynamic_cast< Auxiliary_type* > (tmp.get ()));

            if (r.get ())
              tmp.release ();
            else
              throw ::xsd::cxx::tree::not_derived< wchar_t > ();

            this->Auxiliary_.push_back (::std::move (r));
            continue;
          }
        }

        break;
      }

      while (p.more_attributes ())
      {
        const xercesc::DOMAttr& i (p.next_attribute ());
        const ::xsd::cxx::xml::qualified_name< wchar_t > n (
          ::xsd::cxx::xml::dom::name< wchar_t > (i));

        if (n.name () == L"n" && n.namespace_ ().empty ())
        {
          this->n_.set (n_traits::create (i, f, this));
          continue;
        }
      }

      if (!n_.present ())
      {
        throw ::xsd::cxx::tree::expected_attribute< wchar_t > (
          L"n",
          L"");
      }
    }

    AuxiliarySetType* AuxiliarySetType::
    _clone (::xml_schema::flags f,
            ::xml_schema::container* c) const
    {
      return new class AuxiliarySetType (*this, f, c);
    }

    AuxiliarySetType& AuxiliarySetType::
    operator= (const AuxiliarySetType& x)
    {
      if (this != &x)
      {
        static_cast< ::xml_schema::type& > (*this) = x;
        this->Auxiliary_ = x.Auxiliary_;
        this->n_ = x.n_;
      }

      return *this;
    }

    AuxiliarySetType::
    ~AuxiliarySetType ()
    {
    }

    // AuxiliaryBaseType
    //

    AuxiliaryBaseType::
    AuxiliaryBaseType ()
    : ::xsd::qif30::DrawableBaseType ()
    {
    }

    AuxiliaryBaseType::
    AuxiliaryBaseType (const id_type& id)
    : ::xsd::qif30::DrawableBaseType (id)
    {
    }

    AuxiliaryBaseType::
    AuxiliaryBaseType (const AuxiliaryBaseType& x,
                       ::xml_schema::flags f,
                       ::xml_schema::container* c)
    : ::xsd::qif30::DrawableBaseType (x, f, c)
    {
    }

    AuxiliaryBaseType::
    AuxiliaryBaseType (const xercesc::DOMElement& e,
                       ::xml_schema::flags f,
                       ::xml_schema::container* c)
    : ::xsd::qif30::DrawableBaseType (e, f, c)
    {
    }

    AuxiliaryBaseType::
    ~AuxiliaryBaseType ()
    {
    }

    // PointAuxiliaryType
    //

    PointAuxiliaryType::
    PointAuxiliaryType ()
    : ::xsd::qif30::AuxiliaryBaseType (),
      XYZ_ (this)
    {
    }

    PointAuxiliaryType::
    PointAuxiliaryType (const id_type& id,
                        const XYZ_type& XYZ)
    : ::xsd::qif30::AuxiliaryBaseType (id),
      XYZ_ (XYZ, this)
    {
    }

    PointAuxiliaryType::
    PointAuxiliaryType (const id_type& id,
                        ::std::unique_ptr< XYZ_type > XYZ)
    : ::xsd::qif30::AuxiliaryBaseType (id),
      XYZ_ (std::move (XYZ), this)
    {
    }

    PointAuxiliaryType::
    PointAuxiliaryType (const PointAuxiliaryType& x,
                        ::xml_schema::flags f,
                        ::xml_schema::container* c)
    : ::xsd::qif30::AuxiliaryBaseType (x, f, c),
      XYZ_ (x.XYZ_, f, this)
    {
    }

    PointAuxiliaryType::
    PointAuxiliaryType (const xercesc::DOMElement& e,
                        ::xml_schema::flags f,
                        ::xml_schema::container* c)
    : ::xsd::qif30::AuxiliaryBaseType (e, f | ::xml_schema::flags::base, c),
      XYZ_ (this)
    {
      if ((f & ::xml_schema::flags::base) == 0)
      {
        ::xsd::cxx::xml::dom::parser< wchar_t > p (e, true, false, true);
        this->parse (p, f);
      }
    }

    void PointAuxiliaryType::
    parse (::xsd::cxx::xml::dom::parser< wchar_t >& p,
           ::xml_schema::flags f)
    {
      this->::xsd::qif30::AuxiliaryBaseType::parse (p, f);

      for (; p.more_content (); p.next_content (false))
      {
        const xercesc::DOMElement& i (p.cur_element ());
        const ::xsd::cxx::xml::qualified_name< wchar_t > n (
          ::xsd::cxx::xml::dom::name< wchar_t > (i));

        // XYZ
        //
        if (n.name () == L"XYZ" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< XYZ_type > r (
            XYZ_traits::create (i, f, this));

          if (!XYZ_.present ())
          {
            this->XYZ_.set (::std::move (r));
            continue;
          }
        }

        break;
      }

      if (!XYZ_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< wchar_t > (
          L"XYZ",
          L"http://qifstandards.org/xsd/qif3");
      }
    }

    PointAuxiliaryType* PointAuxiliaryType::
    _clone (::xml_schema::flags f,
            ::xml_schema::container* c) const
    {
      return new class PointAuxiliaryType (*this, f, c);
    }

    PointAuxiliaryType& PointAuxiliaryType::
    operator= (const PointAuxiliaryType& x)
    {
      if (this != &x)
      {
        static_cast< ::xsd::qif30::AuxiliaryBaseType& > (*this) = x;
        this->XYZ_ = x.XYZ_;
      }

      return *this;
    }

    PointAuxiliaryType::
    ~PointAuxiliaryType ()
    {
    }

    static
    const ::xsd::cxx::tree::type_factory_initializer< 0, wchar_t, PointAuxiliaryType >
    _xsd_PointAuxiliaryType_type_factory_init (
      L"PointAuxiliaryType",
      L"http://qifstandards.org/xsd/qif3");

    // LineAuxiliaryType
    //

    LineAuxiliaryType::
    LineAuxiliaryType ()
    : ::xsd::qif30::AuxiliaryBaseType (),
      StartPoint_ (this),
      EndPoint_ (this),
      LineStyle_ (this)
    {
    }

    LineAuxiliaryType::
    LineAuxiliaryType (const id_type& id,
                       const StartPoint_type& StartPoint,
                       const EndPoint_type& EndPoint)
    : ::xsd::qif30::AuxiliaryBaseType (id),
      StartPoint_ (StartPoint, this),
      EndPoint_ (EndPoint, this),
      LineStyle_ (this)
    {
    }

    LineAuxiliaryType::
    LineAuxiliaryType (const LineAuxiliaryType& x,
                       ::xml_schema::flags f,
                       ::xml_schema::container* c)
    : ::xsd::qif30::AuxiliaryBaseType (x, f, c),
      StartPoint_ (x.StartPoint_, f, this),
      EndPoint_ (x.EndPoint_, f, this),
      LineStyle_ (x.LineStyle_, f, this)
    {
    }

    LineAuxiliaryType::
    LineAuxiliaryType (const xercesc::DOMElement& e,
                       ::xml_schema::flags f,
                       ::xml_schema::container* c)
    : ::xsd::qif30::AuxiliaryBaseType (e, f | ::xml_schema::flags::base, c),
      StartPoint_ (this),
      EndPoint_ (this),
      LineStyle_ (this)
    {
      if ((f & ::xml_schema::flags::base) == 0)
      {
        ::xsd::cxx::xml::dom::parser< wchar_t > p (e, true, false, true);
        this->parse (p, f);
      }
    }

    void LineAuxiliaryType::
    parse (::xsd::cxx::xml::dom::parser< wchar_t >& p,
           ::xml_schema::flags f)
    {
      this->::xsd::qif30::AuxiliaryBaseType::parse (p, f);

      for (; p.more_content (); p.next_content (false))
      {
        const xercesc::DOMElement& i (p.cur_element ());
        const ::xsd::cxx::xml::qualified_name< wchar_t > n (
          ::xsd::cxx::xml::dom::name< wchar_t > (i));

        // StartPoint
        //
        if (n.name () == L"StartPoint" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< StartPoint_type > r (
            StartPoint_traits::create (i, f, this));

          if (!StartPoint_.present ())
          {
            this->StartPoint_.set (::std::move (r));
            continue;
          }
        }

        // EndPoint
        //
        if (n.name () == L"EndPoint" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< EndPoint_type > r (
            EndPoint_traits::create (i, f, this));

          if (!EndPoint_.present ())
          {
            this->EndPoint_.set (::std::move (r));
            continue;
          }
        }

        // LineStyle
        //
        if (n.name () == L"LineStyle" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< LineStyle_type > r (
            LineStyle_traits::create (i, f, this));

          if (!this->LineStyle_)
          {
            this->LineStyle_.set (::std::move (r));
            continue;
          }
        }

        break;
      }

      if (!StartPoint_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< wchar_t > (
          L"StartPoint",
          L"http://qifstandards.org/xsd/qif3");
      }

      if (!EndPoint_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< wchar_t > (
          L"EndPoint",
          L"http://qifstandards.org/xsd/qif3");
      }
    }

    LineAuxiliaryType* LineAuxiliaryType::
    _clone (::xml_schema::flags f,
            ::xml_schema::container* c) const
    {
      return new class LineAuxiliaryType (*this, f, c);
    }

    LineAuxiliaryType& LineAuxiliaryType::
    operator= (const LineAuxiliaryType& x)
    {
      if (this != &x)
      {
        static_cast< ::xsd::qif30::AuxiliaryBaseType& > (*this) = x;
        this->StartPoint_ = x.StartPoint_;
        this->EndPoint_ = x.EndPoint_;
        this->LineStyle_ = x.LineStyle_;
      }

      return *this;
    }

    LineAuxiliaryType::
    ~LineAuxiliaryType ()
    {
    }

    static
    const ::xsd::cxx::tree::type_factory_initializer< 0, wchar_t, LineAuxiliaryType >
    _xsd_LineAuxiliaryType_type_factory_init (
      L"LineAuxiliaryType",
      L"http://qifstandards.org/xsd/qif3");

    // AuxiliaryPlaneBaseType
    //

    AuxiliaryPlaneBaseType::
    AuxiliaryPlaneBaseType ()
    : ::xsd::qif30::AuxiliaryBaseType (),
      Plane_ (this)
    {
    }

    AuxiliaryPlaneBaseType::
    AuxiliaryPlaneBaseType (const id_type& id,
                            const Plane_type& Plane)
    : ::xsd::qif30::AuxiliaryBaseType (id),
      Plane_ (Plane, this)
    {
    }

    AuxiliaryPlaneBaseType::
    AuxiliaryPlaneBaseType (const id_type& id,
                            ::std::unique_ptr< Plane_type > Plane)
    : ::xsd::qif30::AuxiliaryBaseType (id),
      Plane_ (std::move (Plane), this)
    {
    }

    AuxiliaryPlaneBaseType::
    AuxiliaryPlaneBaseType (const AuxiliaryPlaneBaseType& x,
                            ::xml_schema::flags f,
                            ::xml_schema::container* c)
    : ::xsd::qif30::AuxiliaryBaseType (x, f, c),
      Plane_ (x.Plane_, f, this)
    {
    }

    AuxiliaryPlaneBaseType::
    AuxiliaryPlaneBaseType (const xercesc::DOMElement& e,
                            ::xml_schema::flags f,
                            ::xml_schema::container* c)
    : ::xsd::qif30::AuxiliaryBaseType (e, f | ::xml_schema::flags::base, c),
      Plane_ (this)
    {
      if ((f & ::xml_schema::flags::base) == 0)
      {
        ::xsd::cxx::xml::dom::parser< wchar_t > p (e, true, false, true);
        this->parse (p, f);
      }
    }

    void AuxiliaryPlaneBaseType::
    parse (::xsd::cxx::xml::dom::parser< wchar_t >& p,
           ::xml_schema::flags f)
    {
      this->::xsd::qif30::AuxiliaryBaseType::parse (p, f);

      for (; p.more_content (); p.next_content (false))
      {
        const xercesc::DOMElement& i (p.cur_element ());
        const ::xsd::cxx::xml::qualified_name< wchar_t > n (
          ::xsd::cxx::xml::dom::name< wchar_t > (i));

        // Plane
        //
        if (n.name () == L"Plane" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< Plane_type > r (
            Plane_traits::create (i, f, this));

          if (!Plane_.present ())
          {
            this->Plane_.set (::std::move (r));
            continue;
          }
        }

        break;
      }

      if (!Plane_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< wchar_t > (
          L"Plane",
          L"http://qifstandards.org/xsd/qif3");
      }
    }

    AuxiliaryPlaneBaseType& AuxiliaryPlaneBaseType::
    operator= (const AuxiliaryPlaneBaseType& x)
    {
      if (this != &x)
      {
        static_cast< ::xsd::qif30::AuxiliaryBaseType& > (*this) = x;
        this->Plane_ = x.Plane_;
      }

      return *this;
    }

    AuxiliaryPlaneBaseType::
    ~AuxiliaryPlaneBaseType ()
    {
    }

    // PlaneReferenceType
    //

    PlaneReferenceType::
    PlaneReferenceType ()
    : ::xsd::qif30::AuxiliaryPlaneBaseType ()
    {
    }

    PlaneReferenceType::
    PlaneReferenceType (const id_type& id,
                        const Plane_type& Plane)
    : ::xsd::qif30::AuxiliaryPlaneBaseType (id,
                                            Plane)
    {
    }

    PlaneReferenceType::
    PlaneReferenceType (const id_type& id,
                        ::std::unique_ptr< Plane_type > Plane)
    : ::xsd::qif30::AuxiliaryPlaneBaseType (id,
                                            std::move (Plane))
    {
    }

    PlaneReferenceType::
    PlaneReferenceType (const PlaneReferenceType& x,
                        ::xml_schema::flags f,
                        ::xml_schema::container* c)
    : ::xsd::qif30::AuxiliaryPlaneBaseType (x, f, c)
    {
    }

    PlaneReferenceType::
    PlaneReferenceType (const xercesc::DOMElement& e,
                        ::xml_schema::flags f,
                        ::xml_schema::container* c)
    : ::xsd::qif30::AuxiliaryPlaneBaseType (e, f, c)
    {
    }

    PlaneReferenceType* PlaneReferenceType::
    _clone (::xml_schema::flags f,
            ::xml_schema::container* c) const
    {
      return new class PlaneReferenceType (*this, f, c);
    }

    PlaneReferenceType::
    ~PlaneReferenceType ()
    {
    }

    static
    const ::xsd::cxx::tree::type_factory_initializer< 0, wchar_t, PlaneReferenceType >
    _xsd_PlaneReferenceType_type_factory_init (
      L"PlaneReferenceType",
      L"http://qifstandards.org/xsd/qif3");

    static
    const ::xsd::cxx::tree::element_factory_initializer< 0, wchar_t >
    _xsd_PointAuxiliary_element_factory_init (
      L"Auxiliary",
      L"http://qifstandards.org/xsd/qif3",
      L"PointAuxiliary",
      L"http://qifstandards.org/xsd/qif3",
      &::xsd::cxx::tree::factory_impl< ::xsd::qif30::PointAuxiliaryType >);


    static
    const ::xsd::cxx::tree::element_factory_initializer< 0, wchar_t >
    _xsd_LineAuxiliary_element_factory_init (
      L"Auxiliary",
      L"http://qifstandards.org/xsd/qif3",
      L"LineAuxiliary",
      L"http://qifstandards.org/xsd/qif3",
      &::xsd::cxx::tree::factory_impl< ::xsd::qif30::LineAuxiliaryType >);


    static
    const ::xsd::cxx::tree::element_factory_initializer< 0, wchar_t >
    _xsd_PlaneReference_element_factory_init (
      L"Auxiliary",
      L"http://qifstandards.org/xsd/qif3",
      L"PlaneReference",
      L"http://qifstandards.org/xsd/qif3",
      &::xsd::cxx::tree::factory_impl< ::xsd::qif30::PlaneReferenceType >);
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace xsd
{
  namespace qif30
  {
  }
}

#include <ostream>
#include <xsd/cxx/tree/error-handler.hxx>
#include <xsd/cxx/xml/dom/serialization-source.hxx>

#include <xsd/cxx/tree/type-serializer-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_serializer_plate< 0, wchar_t >
  type_serializer_plate_init;
}

namespace xsd
{
  namespace qif30
  {
    void
    operator<< (xercesc::DOMElement& e, const CoordinateSystemSetType& i)
    {
      e << static_cast< const ::xml_schema::type& > (i);

      // CoordinateSystem
      //
      for (CoordinateSystemSetType::CoordinateSystem_const_iterator
           b (i.CoordinateSystem ().begin ()), n (i.CoordinateSystem ().end ());
           b != n; ++b)
      {
        const CoordinateSystemSetType::CoordinateSystem_type& x (*b);

        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"CoordinateSystem",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << x;
      }

      // n
      //
      {
        xercesc::DOMAttr& a (
          ::xsd::cxx::xml::dom::create_attribute (
            L"n",
            e));

        a << i.n ();
      }
    }

    void
    operator<< (xercesc::DOMElement& e, const CADCoordinateSystemType& i)
    {
      e << static_cast< const ::xsd::qif30::DrawableBaseType& > (i);

      // CoordinateSystemCore
      //
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"CoordinateSystemCore",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << i.CoordinateSystemCore ();
      }
    }

    void
    operator<< (xercesc::DOMElement& e, const AuxiliarySetType& i)
    {
      e << static_cast< const ::xml_schema::type& > (i);

      // Auxiliary
      //
      {
        ::xsd::cxx::tree::type_serializer_map< wchar_t >& tsm (
          ::xsd::cxx::tree::type_serializer_map_instance< 0, wchar_t > ());

        for (AuxiliarySetType::Auxiliary_const_iterator
             b (i.Auxiliary ().begin ()), n (i.Auxiliary ().end ());
             b != n; ++b)
        {
          const AuxiliarySetType::Auxiliary_type& x (*b);

          if (typeid (AuxiliarySetType::Auxiliary_type) == typeid (x))
          {
            xercesc::DOMElement& s (
              ::xsd::cxx::xml::dom::create_element (
                L"Auxiliary",
                L"http://qifstandards.org/xsd/qif3",
                e));

            s << x;
          }
          else
            tsm.serialize (
              L"Auxiliary",
              L"http://qifstandards.org/xsd/qif3",
              true, true, e, x);
        }
      }

      // n
      //
      {
        xercesc::DOMAttr& a (
          ::xsd::cxx::xml::dom::create_attribute (
            L"n",
            e));

        a << i.n ();
      }
    }

    void
    operator<< (xercesc::DOMElement& e, const AuxiliaryBaseType& i)
    {
      e << static_cast< const ::xsd::qif30::DrawableBaseType& > (i);
    }

    void
    operator<< (xercesc::DOMElement& e, const PointAuxiliaryType& i)
    {
      e << static_cast< const ::xsd::qif30::AuxiliaryBaseType& > (i);

      // XYZ
      //
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"XYZ",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << i.XYZ ();
      }
    }

    static
    const ::xsd::cxx::tree::type_serializer_initializer< 0, wchar_t, PointAuxiliaryType >
    _xsd_PointAuxiliaryType_type_serializer_init (
      L"PointAuxiliaryType",
      L"http://qifstandards.org/xsd/qif3");


    void
    operator<< (xercesc::DOMElement& e, const LineAuxiliaryType& i)
    {
      e << static_cast< const ::xsd::qif30::AuxiliaryBaseType& > (i);

      // StartPoint
      //
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"StartPoint",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << i.StartPoint ();
      }

      // EndPoint
      //
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"EndPoint",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << i.EndPoint ();
      }

      // LineStyle
      //
      if (i.LineStyle ())
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"LineStyle",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << *i.LineStyle ();
      }
    }

    static
    const ::xsd::cxx::tree::type_serializer_initializer< 0, wchar_t, LineAuxiliaryType >
    _xsd_LineAuxiliaryType_type_serializer_init (
      L"LineAuxiliaryType",
      L"http://qifstandards.org/xsd/qif3");


    void
    operator<< (xercesc::DOMElement& e, const AuxiliaryPlaneBaseType& i)
    {
      e << static_cast< const ::xsd::qif30::AuxiliaryBaseType& > (i);

      // Plane
      //
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"Plane",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << i.Plane ();
      }
    }

    void
    operator<< (xercesc::DOMElement& e, const PlaneReferenceType& i)
    {
      e << static_cast< const ::xsd::qif30::AuxiliaryPlaneBaseType& > (i);
    }

    static
    const ::xsd::cxx::tree::type_serializer_initializer< 0, wchar_t, PlaneReferenceType >
    _xsd_PlaneReferenceType_type_serializer_init (
      L"PlaneReferenceType",
      L"http://qifstandards.org/xsd/qif3");


    static
    const ::xsd::cxx::tree::element_serializer_initializer< 0, wchar_t, ::xsd::qif30::PointAuxiliaryType >
    _xsd_PointAuxiliary_element_serializer_init (
      L"Auxiliary",
      L"http://qifstandards.org/xsd/qif3",
      L"PointAuxiliary",
      L"http://qifstandards.org/xsd/qif3",
      &::xsd::cxx::tree::serializer_impl< ::xsd::qif30::PointAuxiliaryType >);


    static
    const ::xsd::cxx::tree::element_serializer_initializer< 0, wchar_t, ::xsd::qif30::LineAuxiliaryType >
    _xsd_LineAuxiliary_element_serializer_init (
      L"Auxiliary",
      L"http://qifstandards.org/xsd/qif3",
      L"LineAuxiliary",
      L"http://qifstandards.org/xsd/qif3",
      &::xsd::cxx::tree::serializer_impl< ::xsd::qif30::LineAuxiliaryType >);


    static
    const ::xsd::cxx::tree::element_serializer_initializer< 0, wchar_t, ::xsd::qif30::PlaneReferenceType >
    _xsd_PlaneReference_element_serializer_init (
      L"Auxiliary",
      L"http://qifstandards.org/xsd/qif3",
      L"PlaneReference",
      L"http://qifstandards.org/xsd/qif3",
      &::xsd::cxx::tree::serializer_impl< ::xsd::qif30::PlaneReferenceType >);
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

