// Copyright (c) 2005-2023 Code Synthesis.
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis gives permission
// to link this program with the Xerces-C++ library (or with modified
// versions of Xerces-C++ that use the same license as Xerces-C++), and
// distribute linked combinations including the two. You must obey the GNU
// General Public License version 2 in all respects for all of the code
// used other than Xerces-C++. If you modify this copy of the program, you
// may extend this exception to your version of the program, but you are
// not obligated to do so. If you do not wish to do so, delete this
// exception statement from your version.
//
// Furthermore, Code Synthesis makes a special exception for the Free/Libre
// and Open Source Software (FLOSS) which is described in the accompanying
// FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "QIFDocument.hxx"

namespace xsd
{
  namespace qif30
  {
    // QIFDocumentType
    //

    const QIFDocumentType::QPId_type& QIFDocumentType::
    QPId () const
    {
      return this->QPId_.get ();
    }

    QIFDocumentType::QPId_type& QIFDocumentType::
    QPId ()
    {
      return this->QPId_.get ();
    }

    void QIFDocumentType::
    QPId (const QPId_type& x)
    {
      this->QPId_.set (x);
    }

    void QIFDocumentType::
    QPId (::std::unique_ptr< QPId_type > x)
    {
      this->QPId_.set (std::move (x));
    }

    const QIFDocumentType::Attributes_optional& QIFDocumentType::
    Attributes () const
    {
      return this->Attributes_;
    }

    QIFDocumentType::Attributes_optional& QIFDocumentType::
    Attributes ()
    {
      return this->Attributes_;
    }

    void QIFDocumentType::
    Attributes (const Attributes_type& x)
    {
      this->Attributes_.set (x);
    }

    void QIFDocumentType::
    Attributes (const Attributes_optional& x)
    {
      this->Attributes_ = x;
    }

    void QIFDocumentType::
    Attributes (::std::unique_ptr< Attributes_type > x)
    {
      this->Attributes_.set (std::move (x));
    }

    const QIFDocumentType::VersionHistory_optional& QIFDocumentType::
    VersionHistory () const
    {
      return this->VersionHistory_;
    }

    QIFDocumentType::VersionHistory_optional& QIFDocumentType::
    VersionHistory ()
    {
      return this->VersionHistory_;
    }

    void QIFDocumentType::
    VersionHistory (const VersionHistory_type& x)
    {
      this->VersionHistory_.set (x);
    }

    void QIFDocumentType::
    VersionHistory (const VersionHistory_optional& x)
    {
      this->VersionHistory_ = x;
    }

    void QIFDocumentType::
    VersionHistory (::std::unique_ptr< VersionHistory_type > x)
    {
      this->VersionHistory_.set (std::move (x));
    }

    const QIFDocumentType::Version_optional& QIFDocumentType::
    Version () const
    {
      return this->Version_;
    }

    QIFDocumentType::Version_optional& QIFDocumentType::
    Version ()
    {
      return this->Version_;
    }

    void QIFDocumentType::
    Version (const Version_type& x)
    {
      this->Version_.set (x);
    }

    void QIFDocumentType::
    Version (const Version_optional& x)
    {
      this->Version_ = x;
    }

    void QIFDocumentType::
    Version (::std::unique_ptr< Version_type > x)
    {
      this->Version_.set (std::move (x));
    }

    const QIFDocumentType::Header_optional& QIFDocumentType::
    Header () const
    {
      return this->Header_;
    }

    QIFDocumentType::Header_optional& QIFDocumentType::
    Header ()
    {
      return this->Header_;
    }

    void QIFDocumentType::
    Header (const Header_type& x)
    {
      this->Header_.set (x);
    }

    void QIFDocumentType::
    Header (const Header_optional& x)
    {
      this->Header_ = x;
    }

    void QIFDocumentType::
    Header (::std::unique_ptr< Header_type > x)
    {
      this->Header_.set (std::move (x));
    }

    const QIFDocumentType::ValidationCounts_optional& QIFDocumentType::
    ValidationCounts () const
    {
      return this->ValidationCounts_;
    }

    QIFDocumentType::ValidationCounts_optional& QIFDocumentType::
    ValidationCounts ()
    {
      return this->ValidationCounts_;
    }

    void QIFDocumentType::
    ValidationCounts (const ValidationCounts_type& x)
    {
      this->ValidationCounts_.set (x);
    }

    void QIFDocumentType::
    ValidationCounts (const ValidationCounts_optional& x)
    {
      this->ValidationCounts_ = x;
    }

    void QIFDocumentType::
    ValidationCounts (::std::unique_ptr< ValidationCounts_type > x)
    {
      this->ValidationCounts_.set (std::move (x));
    }

    const QIFDocumentType::ProductDataQuality_optional& QIFDocumentType::
    ProductDataQuality () const
    {
      return this->ProductDataQuality_;
    }

    QIFDocumentType::ProductDataQuality_optional& QIFDocumentType::
    ProductDataQuality ()
    {
      return this->ProductDataQuality_;
    }

    void QIFDocumentType::
    ProductDataQuality (const ProductDataQuality_type& x)
    {
      this->ProductDataQuality_.set (x);
    }

    void QIFDocumentType::
    ProductDataQuality (const ProductDataQuality_optional& x)
    {
      this->ProductDataQuality_ = x;
    }

    void QIFDocumentType::
    ProductDataQuality (::std::unique_ptr< ProductDataQuality_type > x)
    {
      this->ProductDataQuality_.set (std::move (x));
    }

    const QIFDocumentType::ExternalQIFReferences_optional& QIFDocumentType::
    ExternalQIFReferences () const
    {
      return this->ExternalQIFReferences_;
    }

    QIFDocumentType::ExternalQIFReferences_optional& QIFDocumentType::
    ExternalQIFReferences ()
    {
      return this->ExternalQIFReferences_;
    }

    void QIFDocumentType::
    ExternalQIFReferences (const ExternalQIFReferences_type& x)
    {
      this->ExternalQIFReferences_.set (x);
    }

    void QIFDocumentType::
    ExternalQIFReferences (const ExternalQIFReferences_optional& x)
    {
      this->ExternalQIFReferences_ = x;
    }

    void QIFDocumentType::
    ExternalQIFReferences (::std::unique_ptr< ExternalQIFReferences_type > x)
    {
      this->ExternalQIFReferences_.set (std::move (x));
    }

    const QIFDocumentType::StandardsDefinitions_optional& QIFDocumentType::
    StandardsDefinitions () const
    {
      return this->StandardsDefinitions_;
    }

    QIFDocumentType::StandardsDefinitions_optional& QIFDocumentType::
    StandardsDefinitions ()
    {
      return this->StandardsDefinitions_;
    }

    void QIFDocumentType::
    StandardsDefinitions (const StandardsDefinitions_type& x)
    {
      this->StandardsDefinitions_.set (x);
    }

    void QIFDocumentType::
    StandardsDefinitions (const StandardsDefinitions_optional& x)
    {
      this->StandardsDefinitions_ = x;
    }

    void QIFDocumentType::
    StandardsDefinitions (::std::unique_ptr< StandardsDefinitions_type > x)
    {
      this->StandardsDefinitions_.set (std::move (x));
    }

    const QIFDocumentType::SoftwareDefinitions_optional& QIFDocumentType::
    SoftwareDefinitions () const
    {
      return this->SoftwareDefinitions_;
    }

    QIFDocumentType::SoftwareDefinitions_optional& QIFDocumentType::
    SoftwareDefinitions ()
    {
      return this->SoftwareDefinitions_;
    }

    void QIFDocumentType::
    SoftwareDefinitions (const SoftwareDefinitions_type& x)
    {
      this->SoftwareDefinitions_.set (x);
    }

    void QIFDocumentType::
    SoftwareDefinitions (const SoftwareDefinitions_optional& x)
    {
      this->SoftwareDefinitions_ = x;
    }

    void QIFDocumentType::
    SoftwareDefinitions (::std::unique_ptr< SoftwareDefinitions_type > x)
    {
      this->SoftwareDefinitions_.set (std::move (x));
    }

    const QIFDocumentType::AlgorithmDefinitions_optional& QIFDocumentType::
    AlgorithmDefinitions () const
    {
      return this->AlgorithmDefinitions_;
    }

    QIFDocumentType::AlgorithmDefinitions_optional& QIFDocumentType::
    AlgorithmDefinitions ()
    {
      return this->AlgorithmDefinitions_;
    }

    void QIFDocumentType::
    AlgorithmDefinitions (const AlgorithmDefinitions_type& x)
    {
      this->AlgorithmDefinitions_.set (x);
    }

    void QIFDocumentType::
    AlgorithmDefinitions (const AlgorithmDefinitions_optional& x)
    {
      this->AlgorithmDefinitions_ = x;
    }

    void QIFDocumentType::
    AlgorithmDefinitions (::std::unique_ptr< AlgorithmDefinitions_type > x)
    {
      this->AlgorithmDefinitions_.set (std::move (x));
    }

    const QIFDocumentType::PreInspectionTraceability_optional& QIFDocumentType::
    PreInspectionTraceability () const
    {
      return this->PreInspectionTraceability_;
    }

    QIFDocumentType::PreInspectionTraceability_optional& QIFDocumentType::
    PreInspectionTraceability ()
    {
      return this->PreInspectionTraceability_;
    }

    void QIFDocumentType::
    PreInspectionTraceability (const PreInspectionTraceability_type& x)
    {
      this->PreInspectionTraceability_.set (x);
    }

    void QIFDocumentType::
    PreInspectionTraceability (const PreInspectionTraceability_optional& x)
    {
      this->PreInspectionTraceability_ = x;
    }

    void QIFDocumentType::
    PreInspectionTraceability (::std::unique_ptr< PreInspectionTraceability_type > x)
    {
      this->PreInspectionTraceability_.set (std::move (x));
    }

    const QIFDocumentType::FileUnits_optional& QIFDocumentType::
    FileUnits () const
    {
      return this->FileUnits_;
    }

    QIFDocumentType::FileUnits_optional& QIFDocumentType::
    FileUnits ()
    {
      return this->FileUnits_;
    }

    void QIFDocumentType::
    FileUnits (const FileUnits_type& x)
    {
      this->FileUnits_.set (x);
    }

    void QIFDocumentType::
    FileUnits (const FileUnits_optional& x)
    {
      this->FileUnits_ = x;
    }

    void QIFDocumentType::
    FileUnits (::std::unique_ptr< FileUnits_type > x)
    {
      this->FileUnits_.set (std::move (x));
    }

    const QIFDocumentType::DatumDefinitions_optional& QIFDocumentType::
    DatumDefinitions () const
    {
      return this->DatumDefinitions_;
    }

    QIFDocumentType::DatumDefinitions_optional& QIFDocumentType::
    DatumDefinitions ()
    {
      return this->DatumDefinitions_;
    }

    void QIFDocumentType::
    DatumDefinitions (const DatumDefinitions_type& x)
    {
      this->DatumDefinitions_.set (x);
    }

    void QIFDocumentType::
    DatumDefinitions (const DatumDefinitions_optional& x)
    {
      this->DatumDefinitions_ = x;
    }

    void QIFDocumentType::
    DatumDefinitions (::std::unique_ptr< DatumDefinitions_type > x)
    {
      this->DatumDefinitions_.set (std::move (x));
    }

    const QIFDocumentType::DatumTargetDefinitions_optional& QIFDocumentType::
    DatumTargetDefinitions () const
    {
      return this->DatumTargetDefinitions_;
    }

    QIFDocumentType::DatumTargetDefinitions_optional& QIFDocumentType::
    DatumTargetDefinitions ()
    {
      return this->DatumTargetDefinitions_;
    }

    void QIFDocumentType::
    DatumTargetDefinitions (const DatumTargetDefinitions_type& x)
    {
      this->DatumTargetDefinitions_.set (x);
    }

    void QIFDocumentType::
    DatumTargetDefinitions (const DatumTargetDefinitions_optional& x)
    {
      this->DatumTargetDefinitions_ = x;
    }

    void QIFDocumentType::
    DatumTargetDefinitions (::std::unique_ptr< DatumTargetDefinitions_type > x)
    {
      this->DatumTargetDefinitions_.set (std::move (x));
    }

    const QIFDocumentType::Transforms_optional& QIFDocumentType::
    Transforms () const
    {
      return this->Transforms_;
    }

    QIFDocumentType::Transforms_optional& QIFDocumentType::
    Transforms ()
    {
      return this->Transforms_;
    }

    void QIFDocumentType::
    Transforms (const Transforms_type& x)
    {
      this->Transforms_.set (x);
    }

    void QIFDocumentType::
    Transforms (const Transforms_optional& x)
    {
      this->Transforms_ = x;
    }

    void QIFDocumentType::
    Transforms (::std::unique_ptr< Transforms_type > x)
    {
      this->Transforms_.set (std::move (x));
    }

    const QIFDocumentType::CoordinateSystems_optional& QIFDocumentType::
    CoordinateSystems () const
    {
      return this->CoordinateSystems_;
    }

    QIFDocumentType::CoordinateSystems_optional& QIFDocumentType::
    CoordinateSystems ()
    {
      return this->CoordinateSystems_;
    }

    void QIFDocumentType::
    CoordinateSystems (const CoordinateSystems_type& x)
    {
      this->CoordinateSystems_.set (x);
    }

    void QIFDocumentType::
    CoordinateSystems (const CoordinateSystems_optional& x)
    {
      this->CoordinateSystems_ = x;
    }

    void QIFDocumentType::
    CoordinateSystems (::std::unique_ptr< CoordinateSystems_type > x)
    {
      this->CoordinateSystems_.set (std::move (x));
    }

    const QIFDocumentType::DatumReferenceFrames_optional& QIFDocumentType::
    DatumReferenceFrames () const
    {
      return this->DatumReferenceFrames_;
    }

    QIFDocumentType::DatumReferenceFrames_optional& QIFDocumentType::
    DatumReferenceFrames ()
    {
      return this->DatumReferenceFrames_;
    }

    void QIFDocumentType::
    DatumReferenceFrames (const DatumReferenceFrames_type& x)
    {
      this->DatumReferenceFrames_.set (x);
    }

    void QIFDocumentType::
    DatumReferenceFrames (const DatumReferenceFrames_optional& x)
    {
      this->DatumReferenceFrames_ = x;
    }

    void QIFDocumentType::
    DatumReferenceFrames (::std::unique_ptr< DatumReferenceFrames_type > x)
    {
      this->DatumReferenceFrames_.set (std::move (x));
    }

    const QIFDocumentType::MeasurementResources_optional& QIFDocumentType::
    MeasurementResources () const
    {
      return this->MeasurementResources_;
    }

    QIFDocumentType::MeasurementResources_optional& QIFDocumentType::
    MeasurementResources ()
    {
      return this->MeasurementResources_;
    }

    void QIFDocumentType::
    MeasurementResources (const MeasurementResources_type& x)
    {
      this->MeasurementResources_.set (x);
    }

    void QIFDocumentType::
    MeasurementResources (const MeasurementResources_optional& x)
    {
      this->MeasurementResources_ = x;
    }

    void QIFDocumentType::
    MeasurementResources (::std::unique_ptr< MeasurementResources_type > x)
    {
      this->MeasurementResources_.set (std::move (x));
    }

    const QIFDocumentType::ThreadSpecifications_optional& QIFDocumentType::
    ThreadSpecifications () const
    {
      return this->ThreadSpecifications_;
    }

    QIFDocumentType::ThreadSpecifications_optional& QIFDocumentType::
    ThreadSpecifications ()
    {
      return this->ThreadSpecifications_;
    }

    void QIFDocumentType::
    ThreadSpecifications (const ThreadSpecifications_type& x)
    {
      this->ThreadSpecifications_.set (x);
    }

    void QIFDocumentType::
    ThreadSpecifications (const ThreadSpecifications_optional& x)
    {
      this->ThreadSpecifications_ = x;
    }

    void QIFDocumentType::
    ThreadSpecifications (::std::unique_ptr< ThreadSpecifications_type > x)
    {
      this->ThreadSpecifications_.set (std::move (x));
    }

    const QIFDocumentType::Product_optional& QIFDocumentType::
    Product () const
    {
      return this->Product_;
    }

    QIFDocumentType::Product_optional& QIFDocumentType::
    Product ()
    {
      return this->Product_;
    }

    void QIFDocumentType::
    Product (const Product_type& x)
    {
      this->Product_.set (x);
    }

    void QIFDocumentType::
    Product (const Product_optional& x)
    {
      this->Product_ = x;
    }

    void QIFDocumentType::
    Product (::std::unique_ptr< Product_type > x)
    {
      this->Product_.set (std::move (x));
    }

    const QIFDocumentType::Features_optional& QIFDocumentType::
    Features () const
    {
      return this->Features_;
    }

    QIFDocumentType::Features_optional& QIFDocumentType::
    Features ()
    {
      return this->Features_;
    }

    void QIFDocumentType::
    Features (const Features_type& x)
    {
      this->Features_.set (x);
    }

    void QIFDocumentType::
    Features (const Features_optional& x)
    {
      this->Features_ = x;
    }

    void QIFDocumentType::
    Features (::std::unique_ptr< Features_type > x)
    {
      this->Features_.set (std::move (x));
    }

    const QIFDocumentType::FeatureZones_optional& QIFDocumentType::
    FeatureZones () const
    {
      return this->FeatureZones_;
    }

    QIFDocumentType::FeatureZones_optional& QIFDocumentType::
    FeatureZones ()
    {
      return this->FeatureZones_;
    }

    void QIFDocumentType::
    FeatureZones (const FeatureZones_type& x)
    {
      this->FeatureZones_.set (x);
    }

    void QIFDocumentType::
    FeatureZones (const FeatureZones_optional& x)
    {
      this->FeatureZones_ = x;
    }

    void QIFDocumentType::
    FeatureZones (::std::unique_ptr< FeatureZones_type > x)
    {
      this->FeatureZones_.set (std::move (x));
    }

    const QIFDocumentType::Characteristics_optional& QIFDocumentType::
    Characteristics () const
    {
      return this->Characteristics_;
    }

    QIFDocumentType::Characteristics_optional& QIFDocumentType::
    Characteristics ()
    {
      return this->Characteristics_;
    }

    void QIFDocumentType::
    Characteristics (const Characteristics_type& x)
    {
      this->Characteristics_.set (x);
    }

    void QIFDocumentType::
    Characteristics (const Characteristics_optional& x)
    {
      this->Characteristics_ = x;
    }

    void QIFDocumentType::
    Characteristics (::std::unique_ptr< Characteristics_type > x)
    {
      this->Characteristics_.set (std::move (x));
    }

    const QIFDocumentType::Plan_optional& QIFDocumentType::
    Plan () const
    {
      return this->Plan_;
    }

    QIFDocumentType::Plan_optional& QIFDocumentType::
    Plan ()
    {
      return this->Plan_;
    }

    void QIFDocumentType::
    Plan (const Plan_type& x)
    {
      this->Plan_.set (x);
    }

    void QIFDocumentType::
    Plan (const Plan_optional& x)
    {
      this->Plan_ = x;
    }

    void QIFDocumentType::
    Plan (::std::unique_ptr< Plan_type > x)
    {
      this->Plan_.set (std::move (x));
    }

    const QIFDocumentType::Results_optional& QIFDocumentType::
    Results () const
    {
      return this->Results_;
    }

    QIFDocumentType::Results_optional& QIFDocumentType::
    Results ()
    {
      return this->Results_;
    }

    void QIFDocumentType::
    Results (const Results_type& x)
    {
      this->Results_.set (x);
    }

    void QIFDocumentType::
    Results (const Results_optional& x)
    {
      this->Results_ = x;
    }

    void QIFDocumentType::
    Results (::std::unique_ptr< Results_type > x)
    {
      this->Results_.set (std::move (x));
    }

    const QIFDocumentType::Statistics_optional& QIFDocumentType::
    Statistics () const
    {
      return this->Statistics_;
    }

    QIFDocumentType::Statistics_optional& QIFDocumentType::
    Statistics ()
    {
      return this->Statistics_;
    }

    void QIFDocumentType::
    Statistics (const Statistics_type& x)
    {
      this->Statistics_.set (x);
    }

    void QIFDocumentType::
    Statistics (const Statistics_optional& x)
    {
      this->Statistics_ = x;
    }

    void QIFDocumentType::
    Statistics (::std::unique_ptr< Statistics_type > x)
    {
      this->Statistics_.set (std::move (x));
    }

    const QIFDocumentType::ManufacturingProcessTraceabilities_optional& QIFDocumentType::
    ManufacturingProcessTraceabilities () const
    {
      return this->ManufacturingProcessTraceabilities_;
    }

    QIFDocumentType::ManufacturingProcessTraceabilities_optional& QIFDocumentType::
    ManufacturingProcessTraceabilities ()
    {
      return this->ManufacturingProcessTraceabilities_;
    }

    void QIFDocumentType::
    ManufacturingProcessTraceabilities (const ManufacturingProcessTraceabilities_type& x)
    {
      this->ManufacturingProcessTraceabilities_.set (x);
    }

    void QIFDocumentType::
    ManufacturingProcessTraceabilities (const ManufacturingProcessTraceabilities_optional& x)
    {
      this->ManufacturingProcessTraceabilities_ = x;
    }

    void QIFDocumentType::
    ManufacturingProcessTraceabilities (::std::unique_ptr< ManufacturingProcessTraceabilities_type > x)
    {
      this->ManufacturingProcessTraceabilities_.set (std::move (x));
    }

    const QIFDocumentType::Rules_optional& QIFDocumentType::
    Rules () const
    {
      return this->Rules_;
    }

    QIFDocumentType::Rules_optional& QIFDocumentType::
    Rules ()
    {
      return this->Rules_;
    }

    void QIFDocumentType::
    Rules (const Rules_type& x)
    {
      this->Rules_.set (x);
    }

    void QIFDocumentType::
    Rules (const Rules_optional& x)
    {
      this->Rules_ = x;
    }

    void QIFDocumentType::
    Rules (::std::unique_ptr< Rules_type > x)
    {
      this->Rules_.set (std::move (x));
    }

    const QIFDocumentType::UserDataXML_optional& QIFDocumentType::
    UserDataXML () const
    {
      return this->UserDataXML_;
    }

    QIFDocumentType::UserDataXML_optional& QIFDocumentType::
    UserDataXML ()
    {
      return this->UserDataXML_;
    }

    void QIFDocumentType::
    UserDataXML (const UserDataXML_type& x)
    {
      this->UserDataXML_.set (x);
    }

    void QIFDocumentType::
    UserDataXML (const UserDataXML_optional& x)
    {
      this->UserDataXML_ = x;
    }

    void QIFDocumentType::
    UserDataXML (::std::unique_ptr< UserDataXML_type > x)
    {
      this->UserDataXML_.set (std::move (x));
    }

    const QIFDocumentType::Signature_optional& QIFDocumentType::
    Signature () const
    {
      return this->Signature_;
    }

    QIFDocumentType::Signature_optional& QIFDocumentType::
    Signature ()
    {
      return this->Signature_;
    }

    void QIFDocumentType::
    Signature (const Signature_type& x)
    {
      this->Signature_.set (x);
    }

    void QIFDocumentType::
    Signature (const Signature_optional& x)
    {
      this->Signature_ = x;
    }

    void QIFDocumentType::
    Signature (::std::unique_ptr< Signature_type > x)
    {
      this->Signature_.set (std::move (x));
    }

    const QIFDocumentType::versionQIF_type& QIFDocumentType::
    versionQIF () const
    {
      return this->versionQIF_.get ();
    }

    const QIFDocumentType::versionQIF_type& QIFDocumentType::
    versionQIF_default_value ()
    {
      return versionQIF_default_value_;
    }

    const QIFDocumentType::idMax_type& QIFDocumentType::
    idMax () const
    {
      return this->idMax_.get ();
    }

    QIFDocumentType::idMax_type& QIFDocumentType::
    idMax ()
    {
      return this->idMax_.get ();
    }

    void QIFDocumentType::
    idMax (const idMax_type& x)
    {
      this->idMax_.set (x);
    }


    // QIFDocumentHeaderType
    //

    const QIFDocumentHeaderType::Application_optional& QIFDocumentHeaderType::
    Application () const
    {
      return this->Application_;
    }

    QIFDocumentHeaderType::Application_optional& QIFDocumentHeaderType::
    Application ()
    {
      return this->Application_;
    }

    void QIFDocumentHeaderType::
    Application (const Application_type& x)
    {
      this->Application_.set (x);
    }

    void QIFDocumentHeaderType::
    Application (const Application_optional& x)
    {
      this->Application_ = x;
    }

    void QIFDocumentHeaderType::
    Application (::std::unique_ptr< Application_type > x)
    {
      this->Application_.set (std::move (x));
    }

    const QIFDocumentHeaderType::Author_optional& QIFDocumentHeaderType::
    Author () const
    {
      return this->Author_;
    }

    QIFDocumentHeaderType::Author_optional& QIFDocumentHeaderType::
    Author ()
    {
      return this->Author_;
    }

    void QIFDocumentHeaderType::
    Author (const Author_type& x)
    {
      this->Author_.set (x);
    }

    void QIFDocumentHeaderType::
    Author (const Author_optional& x)
    {
      this->Author_ = x;
    }

    void QIFDocumentHeaderType::
    Author (::std::unique_ptr< Author_type > x)
    {
      this->Author_.set (std::move (x));
    }

    const QIFDocumentHeaderType::ApplicationSource_optional& QIFDocumentHeaderType::
    ApplicationSource () const
    {
      return this->ApplicationSource_;
    }

    QIFDocumentHeaderType::ApplicationSource_optional& QIFDocumentHeaderType::
    ApplicationSource ()
    {
      return this->ApplicationSource_;
    }

    void QIFDocumentHeaderType::
    ApplicationSource (const ApplicationSource_type& x)
    {
      this->ApplicationSource_.set (x);
    }

    void QIFDocumentHeaderType::
    ApplicationSource (const ApplicationSource_optional& x)
    {
      this->ApplicationSource_ = x;
    }

    void QIFDocumentHeaderType::
    ApplicationSource (::std::unique_ptr< ApplicationSource_type > x)
    {
      this->ApplicationSource_.set (std::move (x));
    }

    const QIFDocumentHeaderType::Description_optional& QIFDocumentHeaderType::
    Description () const
    {
      return this->Description_;
    }

    QIFDocumentHeaderType::Description_optional& QIFDocumentHeaderType::
    Description ()
    {
      return this->Description_;
    }

    void QIFDocumentHeaderType::
    Description (const Description_type& x)
    {
      this->Description_.set (x);
    }

    void QIFDocumentHeaderType::
    Description (const Description_optional& x)
    {
      this->Description_ = x;
    }

    void QIFDocumentHeaderType::
    Description (::std::unique_ptr< Description_type > x)
    {
      this->Description_.set (std::move (x));
    }

    const QIFDocumentHeaderType::Scope_optional& QIFDocumentHeaderType::
    Scope () const
    {
      return this->Scope_;
    }

    QIFDocumentHeaderType::Scope_optional& QIFDocumentHeaderType::
    Scope ()
    {
      return this->Scope_;
    }

    void QIFDocumentHeaderType::
    Scope (const Scope_type& x)
    {
      this->Scope_.set (x);
    }

    void QIFDocumentHeaderType::
    Scope (const Scope_optional& x)
    {
      this->Scope_ = x;
    }

    void QIFDocumentHeaderType::
    Scope (::std::unique_ptr< Scope_type > x)
    {
      this->Scope_.set (std::move (x));
    }


    // ExternalQIFReferencesType
    //

    const ExternalQIFReferencesType::ExternalQIFDocument_sequence& ExternalQIFReferencesType::
    ExternalQIFDocument () const
    {
      return this->ExternalQIFDocument_;
    }

    ExternalQIFReferencesType::ExternalQIFDocument_sequence& ExternalQIFReferencesType::
    ExternalQIFDocument ()
    {
      return this->ExternalQIFDocument_;
    }

    void ExternalQIFReferencesType::
    ExternalQIFDocument (const ExternalQIFDocument_sequence& s)
    {
      this->ExternalQIFDocument_ = s;
    }

    const ExternalQIFReferencesType::n_type& ExternalQIFReferencesType::
    n () const
    {
      return this->n_.get ();
    }

    ExternalQIFReferencesType::n_type& ExternalQIFReferencesType::
    n ()
    {
      return this->n_.get ();
    }

    void ExternalQIFReferencesType::
    n (const n_type& x)
    {
      this->n_.set (x);
    }

    void ExternalQIFReferencesType::
    n (::std::unique_ptr< n_type > x)
    {
      this->n_.set (std::move (x));
    }


    // ExternalQIFDocumentReferenceType
    //

    const ExternalQIFDocumentReferenceType::QPId_type& ExternalQIFDocumentReferenceType::
    QPId () const
    {
      return this->QPId_.get ();
    }

    ExternalQIFDocumentReferenceType::QPId_type& ExternalQIFDocumentReferenceType::
    QPId ()
    {
      return this->QPId_.get ();
    }

    void ExternalQIFDocumentReferenceType::
    QPId (const QPId_type& x)
    {
      this->QPId_.set (x);
    }

    void ExternalQIFDocumentReferenceType::
    QPId (::std::unique_ptr< QPId_type > x)
    {
      this->QPId_.set (std::move (x));
    }

    const ExternalQIFDocumentReferenceType::URI_optional& ExternalQIFDocumentReferenceType::
    URI () const
    {
      return this->URI_;
    }

    ExternalQIFDocumentReferenceType::URI_optional& ExternalQIFDocumentReferenceType::
    URI ()
    {
      return this->URI_;
    }

    void ExternalQIFDocumentReferenceType::
    URI (const URI_type& x)
    {
      this->URI_.set (x);
    }

    void ExternalQIFDocumentReferenceType::
    URI (const URI_optional& x)
    {
      this->URI_ = x;
    }

    void ExternalQIFDocumentReferenceType::
    URI (::std::unique_ptr< URI_type > x)
    {
      this->URI_.set (std::move (x));
    }

    const ExternalQIFDocumentReferenceType::Description_optional& ExternalQIFDocumentReferenceType::
    Description () const
    {
      return this->Description_;
    }

    ExternalQIFDocumentReferenceType::Description_optional& ExternalQIFDocumentReferenceType::
    Description ()
    {
      return this->Description_;
    }

    void ExternalQIFDocumentReferenceType::
    Description (const Description_type& x)
    {
      this->Description_.set (x);
    }

    void ExternalQIFDocumentReferenceType::
    Description (const Description_optional& x)
    {
      this->Description_ = x;
    }

    void ExternalQIFDocumentReferenceType::
    Description (::std::unique_ptr< Description_type > x)
    {
      this->Description_.set (std::move (x));
    }

    const ExternalQIFDocumentReferenceType::id_type& ExternalQIFDocumentReferenceType::
    id () const
    {
      return this->id_.get ();
    }

    ExternalQIFDocumentReferenceType::id_type& ExternalQIFDocumentReferenceType::
    id ()
    {
      return this->id_.get ();
    }

    void ExternalQIFDocumentReferenceType::
    id (const id_type& x)
    {
      this->id_.set (x);
    }

    void ExternalQIFDocumentReferenceType::
    id (::std::unique_ptr< id_type > x)
    {
      this->id_.set (std::move (x));
    }
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

#include <xsd/cxx/tree/type-factory-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_factory_plate< 0, wchar_t >
  type_factory_plate_init;
}

namespace xsd
{
  namespace qif30
  {
    // QIFDocumentType
    //

    const QIFDocumentType::versionQIF_type QIFDocumentType::versionQIF_default_value_ (
      L"3.0.0");

    QIFDocumentType::
    QIFDocumentType ()
    : ::xml_schema::type (),
      QPId_ (this),
      Attributes_ (this),
      VersionHistory_ (this),
      Version_ (this),
      Header_ (this),
      ValidationCounts_ (this),
      ProductDataQuality_ (this),
      ExternalQIFReferences_ (this),
      StandardsDefinitions_ (this),
      SoftwareDefinitions_ (this),
      AlgorithmDefinitions_ (this),
      PreInspectionTraceability_ (this),
      FileUnits_ (this),
      DatumDefinitions_ (this),
      DatumTargetDefinitions_ (this),
      Transforms_ (this),
      CoordinateSystems_ (this),
      DatumReferenceFrames_ (this),
      MeasurementResources_ (this),
      ThreadSpecifications_ (this),
      Product_ (this),
      Features_ (this),
      FeatureZones_ (this),
      Characteristics_ (this),
      Plan_ (this),
      Results_ (this),
      Statistics_ (this),
      ManufacturingProcessTraceabilities_ (this),
      Rules_ (this),
      UserDataXML_ (this),
      Signature_ (this),
      versionQIF_ (versionQIF_default_value (), this),
      idMax_ (this)
    {
    }

    QIFDocumentType::
    QIFDocumentType (const QPId_type& QPId,
                     const idMax_type& idMax)
    : ::xml_schema::type (),
      QPId_ (QPId, this),
      Attributes_ (this),
      VersionHistory_ (this),
      Version_ (this),
      Header_ (this),
      ValidationCounts_ (this),
      ProductDataQuality_ (this),
      ExternalQIFReferences_ (this),
      StandardsDefinitions_ (this),
      SoftwareDefinitions_ (this),
      AlgorithmDefinitions_ (this),
      PreInspectionTraceability_ (this),
      FileUnits_ (this),
      DatumDefinitions_ (this),
      DatumTargetDefinitions_ (this),
      Transforms_ (this),
      CoordinateSystems_ (this),
      DatumReferenceFrames_ (this),
      MeasurementResources_ (this),
      ThreadSpecifications_ (this),
      Product_ (this),
      Features_ (this),
      FeatureZones_ (this),
      Characteristics_ (this),
      Plan_ (this),
      Results_ (this),
      Statistics_ (this),
      ManufacturingProcessTraceabilities_ (this),
      Rules_ (this),
      UserDataXML_ (this),
      Signature_ (this),
      versionQIF_ (versionQIF_default_value (), this),
      idMax_ (idMax, this)
    {
    }

    QIFDocumentType::
    QIFDocumentType (const QIFDocumentType& x,
                     ::xml_schema::flags f,
                     ::xml_schema::container* c)
    : ::xml_schema::type (x, f, c),
      QPId_ (x.QPId_, f, this),
      Attributes_ (x.Attributes_, f, this),
      VersionHistory_ (x.VersionHistory_, f, this),
      Version_ (x.Version_, f, this),
      Header_ (x.Header_, f, this),
      ValidationCounts_ (x.ValidationCounts_, f, this),
      ProductDataQuality_ (x.ProductDataQuality_, f, this),
      ExternalQIFReferences_ (x.ExternalQIFReferences_, f, this),
      StandardsDefinitions_ (x.StandardsDefinitions_, f, this),
      SoftwareDefinitions_ (x.SoftwareDefinitions_, f, this),
      AlgorithmDefinitions_ (x.AlgorithmDefinitions_, f, this),
      PreInspectionTraceability_ (x.PreInspectionTraceability_, f, this),
      FileUnits_ (x.FileUnits_, f, this),
      DatumDefinitions_ (x.DatumDefinitions_, f, this),
      DatumTargetDefinitions_ (x.DatumTargetDefinitions_, f, this),
      Transforms_ (x.Transforms_, f, this),
      CoordinateSystems_ (x.CoordinateSystems_, f, this),
      DatumReferenceFrames_ (x.DatumReferenceFrames_, f, this),
      MeasurementResources_ (x.MeasurementResources_, f, this),
      ThreadSpecifications_ (x.ThreadSpecifications_, f, this),
      Product_ (x.Product_, f, this),
      Features_ (x.Features_, f, this),
      FeatureZones_ (x.FeatureZones_, f, this),
      Characteristics_ (x.Characteristics_, f, this),
      Plan_ (x.Plan_, f, this),
      Results_ (x.Results_, f, this),
      Statistics_ (x.Statistics_, f, this),
      ManufacturingProcessTraceabilities_ (x.ManufacturingProcessTraceabilities_, f, this),
      Rules_ (x.Rules_, f, this),
      UserDataXML_ (x.UserDataXML_, f, this),
      Signature_ (x.Signature_, f, this),
      versionQIF_ (x.versionQIF_, f, this),
      idMax_ (x.idMax_, f, this)
    {
    }

    QIFDocumentType::
    QIFDocumentType (const xercesc::DOMElement& e,
                     ::xml_schema::flags f,
                     ::xml_schema::container* c)
    : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
      QPId_ (this),
      Attributes_ (this),
      VersionHistory_ (this),
      Version_ (this),
      Header_ (this),
      ValidationCounts_ (this),
      ProductDataQuality_ (this),
      ExternalQIFReferences_ (this),
      StandardsDefinitions_ (this),
      SoftwareDefinitions_ (this),
      AlgorithmDefinitions_ (this),
      PreInspectionTraceability_ (this),
      FileUnits_ (this),
      DatumDefinitions_ (this),
      DatumTargetDefinitions_ (this),
      Transforms_ (this),
      CoordinateSystems_ (this),
      DatumReferenceFrames_ (this),
      MeasurementResources_ (this),
      ThreadSpecifications_ (this),
      Product_ (this),
      Features_ (this),
      FeatureZones_ (this),
      Characteristics_ (this),
      Plan_ (this),
      Results_ (this),
      Statistics_ (this),
      ManufacturingProcessTraceabilities_ (this),
      Rules_ (this),
      UserDataXML_ (this),
      Signature_ (this),
      versionQIF_ (this),
      idMax_ (this)
    {
      if ((f & ::xml_schema::flags::base) == 0)
      {
        ::xsd::cxx::xml::dom::parser< wchar_t > p (e, true, false, true);
        this->parse (p, f);
      }
    }

    void QIFDocumentType::
    parse (::xsd::cxx::xml::dom::parser< wchar_t >& p,
           ::xml_schema::flags f)
    {
      for (; p.more_content (); p.next_content (false))
      {
        const xercesc::DOMElement& i (p.cur_element ());
        const ::xsd::cxx::xml::qualified_name< wchar_t > n (
          ::xsd::cxx::xml::dom::name< wchar_t > (i));

        // QPId
        //
        if (n.name () == L"QPId" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< QPId_type > r (
            QPId_traits::create (i, f, this));

          if (!QPId_.present ())
          {
            this->QPId_.set (::std::move (r));
            continue;
          }
        }

        // Attributes
        //
        if (n.name () == L"Attributes" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< Attributes_type > r (
            Attributes_traits::create (i, f, this));

          if (!this->Attributes_)
          {
            this->Attributes_.set (::std::move (r));
            continue;
          }
        }

        // VersionHistory
        //
        if (n.name () == L"VersionHistory" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< VersionHistory_type > r (
            VersionHistory_traits::create (i, f, this));

          if (!this->VersionHistory_)
          {
            this->VersionHistory_.set (::std::move (r));
            continue;
          }
        }

        // Version
        //
        if (n.name () == L"Version" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< Version_type > r (
            Version_traits::create (i, f, this));

          if (!this->Version_)
          {
            this->Version_.set (::std::move (r));
            continue;
          }
        }

        // Header
        //
        if (n.name () == L"Header" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< Header_type > r (
            Header_traits::create (i, f, this));

          if (!this->Header_)
          {
            this->Header_.set (::std::move (r));
            continue;
          }
        }

        // ValidationCounts
        //
        if (n.name () == L"ValidationCounts" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< ValidationCounts_type > r (
            ValidationCounts_traits::create (i, f, this));

          if (!this->ValidationCounts_)
          {
            this->ValidationCounts_.set (::std::move (r));
            continue;
          }
        }

        // ProductDataQuality
        //
        if (n.name () == L"ProductDataQuality" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< ProductDataQuality_type > r (
            ProductDataQuality_traits::create (i, f, this));

          if (!this->ProductDataQuality_)
          {
            this->ProductDataQuality_.set (::std::move (r));
            continue;
          }
        }

        // ExternalQIFReferences
        //
        if (n.name () == L"ExternalQIFReferences" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< ExternalQIFReferences_type > r (
            ExternalQIFReferences_traits::create (i, f, this));

          if (!this->ExternalQIFReferences_)
          {
            this->ExternalQIFReferences_.set (::std::move (r));
            continue;
          }
        }

        // StandardsDefinitions
        //
        if (n.name () == L"StandardsDefinitions" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< StandardsDefinitions_type > r (
            StandardsDefinitions_traits::create (i, f, this));

          if (!this->StandardsDefinitions_)
          {
            this->StandardsDefinitions_.set (::std::move (r));
            continue;
          }
        }

        // SoftwareDefinitions
        //
        if (n.name () == L"SoftwareDefinitions" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< SoftwareDefinitions_type > r (
            SoftwareDefinitions_traits::create (i, f, this));

          if (!this->SoftwareDefinitions_)
          {
            this->SoftwareDefinitions_.set (::std::move (r));
            continue;
          }
        }

        // AlgorithmDefinitions
        //
        if (n.name () == L"AlgorithmDefinitions" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< AlgorithmDefinitions_type > r (
            AlgorithmDefinitions_traits::create (i, f, this));

          if (!this->AlgorithmDefinitions_)
          {
            this->AlgorithmDefinitions_.set (::std::move (r));
            continue;
          }
        }

        // PreInspectionTraceability
        //
        if (n.name () == L"PreInspectionTraceability" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< PreInspectionTraceability_type > r (
            PreInspectionTraceability_traits::create (i, f, this));

          if (!this->PreInspectionTraceability_)
          {
            this->PreInspectionTraceability_.set (::std::move (r));
            continue;
          }
        }

        // FileUnits
        //
        if (n.name () == L"FileUnits" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< FileUnits_type > r (
            FileUnits_traits::create (i, f, this));

          if (!this->FileUnits_)
          {
            this->FileUnits_.set (::std::move (r));
            continue;
          }
        }

        // DatumDefinitions
        //
        if (n.name () == L"DatumDefinitions" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< DatumDefinitions_type > r (
            DatumDefinitions_traits::create (i, f, this));

          if (!this->DatumDefinitions_)
          {
            this->DatumDefinitions_.set (::std::move (r));
            continue;
          }
        }

        // DatumTargetDefinitions
        //
        if (n.name () == L"DatumTargetDefinitions" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< DatumTargetDefinitions_type > r (
            DatumTargetDefinitions_traits::create (i, f, this));

          if (!this->DatumTargetDefinitions_)
          {
            this->DatumTargetDefinitions_.set (::std::move (r));
            continue;
          }
        }

        // Transforms
        //
        if (n.name () == L"Transforms" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< Transforms_type > r (
            Transforms_traits::create (i, f, this));

          if (!this->Transforms_)
          {
            this->Transforms_.set (::std::move (r));
            continue;
          }
        }

        // CoordinateSystems
        //
        if (n.name () == L"CoordinateSystems" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< CoordinateSystems_type > r (
            CoordinateSystems_traits::create (i, f, this));

          if (!this->CoordinateSystems_)
          {
            this->CoordinateSystems_.set (::std::move (r));
            continue;
          }
        }

        // DatumReferenceFrames
        //
        if (n.name () == L"DatumReferenceFrames" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< DatumReferenceFrames_type > r (
            DatumReferenceFrames_traits::create (i, f, this));

          if (!this->DatumReferenceFrames_)
          {
            this->DatumReferenceFrames_.set (::std::move (r));
            continue;
          }
        }

        // MeasurementResources
        //
        if (n.name () == L"MeasurementResources" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< MeasurementResources_type > r (
            MeasurementResources_traits::create (i, f, this));

          if (!this->MeasurementResources_)
          {
            this->MeasurementResources_.set (::std::move (r));
            continue;
          }
        }

        // ThreadSpecifications
        //
        if (n.name () == L"ThreadSpecifications" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< ThreadSpecifications_type > r (
            ThreadSpecifications_traits::create (i, f, this));

          if (!this->ThreadSpecifications_)
          {
            this->ThreadSpecifications_.set (::std::move (r));
            continue;
          }
        }

        // Product
        //
        if (n.name () == L"Product" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< Product_type > r (
            Product_traits::create (i, f, this));

          if (!this->Product_)
          {
            this->Product_.set (::std::move (r));
            continue;
          }
        }

        // Features
        //
        if (n.name () == L"Features" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< Features_type > r (
            Features_traits::create (i, f, this));

          if (!this->Features_)
          {
            this->Features_.set (::std::move (r));
            continue;
          }
        }

        // FeatureZones
        //
        if (n.name () == L"FeatureZones" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< FeatureZones_type > r (
            FeatureZones_traits::create (i, f, this));

          if (!this->FeatureZones_)
          {
            this->FeatureZones_.set (::std::move (r));
            continue;
          }
        }

        // Characteristics
        //
        if (n.name () == L"Characteristics" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< Characteristics_type > r (
            Characteristics_traits::create (i, f, this));

          if (!this->Characteristics_)
          {
            this->Characteristics_.set (::std::move (r));
            continue;
          }
        }

        // Plan
        //
        if (n.name () == L"Plan" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< Plan_type > r (
            Plan_traits::create (i, f, this));

          if (!this->Plan_)
          {
            this->Plan_.set (::std::move (r));
            continue;
          }
        }

        // Results
        //
        if (n.name () == L"Results" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< Results_type > r (
            Results_traits::create (i, f, this));

          if (!this->Results_)
          {
            this->Results_.set (::std::move (r));
            continue;
          }
        }

        // Statistics
        //
        if (n.name () == L"Statistics" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< Statistics_type > r (
            Statistics_traits::create (i, f, this));

          if (!this->Statistics_)
          {
            this->Statistics_.set (::std::move (r));
            continue;
          }
        }

        // ManufacturingProcessTraceabilities
        //
        if (n.name () == L"ManufacturingProcessTraceabilities" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< ManufacturingProcessTraceabilities_type > r (
            ManufacturingProcessTraceabilities_traits::create (i, f, this));

          if (!this->ManufacturingProcessTraceabilities_)
          {
            this->ManufacturingProcessTraceabilities_.set (::std::move (r));
            continue;
          }
        }

        // Rules
        //
        if (n.name () == L"Rules" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< Rules_type > r (
            Rules_traits::create (i, f, this));

          if (!this->Rules_)
          {
            this->Rules_.set (::std::move (r));
            continue;
          }
        }

        // UserDataXML
        //
        if (n.name () == L"UserDataXML" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< UserDataXML_type > r (
            UserDataXML_traits::create (i, f, this));

          if (!this->UserDataXML_)
          {
            this->UserDataXML_.set (::std::move (r));
            continue;
          }
        }

        // Signature
        //
        if (n.name () == L"Signature" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< Signature_type > r (
            Signature_traits::create (i, f, this));

          if (!this->Signature_)
          {
            this->Signature_.set (::std::move (r));
            continue;
          }
        }

        break;
      }

      if (!QPId_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< wchar_t > (
          L"QPId",
          L"http://qifstandards.org/xsd/qif3");
      }

      while (p.more_attributes ())
      {
        const xercesc::DOMAttr& i (p.next_attribute ());
        const ::xsd::cxx::xml::qualified_name< wchar_t > n (
          ::xsd::cxx::xml::dom::name< wchar_t > (i));

        if (n.name () == L"versionQIF" && n.namespace_ ().empty ())
        {
          this->versionQIF_.set (versionQIF_traits::create (i, f, this));
          continue;
        }

        if (n.name () == L"idMax" && n.namespace_ ().empty ())
        {
          this->idMax_.set (idMax_traits::create (i, f, this));
          continue;
        }
      }

      if (!versionQIF_.present ())
      {
        this->versionQIF_.set (versionQIF_default_value ());
      }

      if (!idMax_.present ())
      {
        throw ::xsd::cxx::tree::expected_attribute< wchar_t > (
          L"idMax",
          L"");
      }
    }

    QIFDocumentType* QIFDocumentType::
    _clone (::xml_schema::flags f,
            ::xml_schema::container* c) const
    {
      return new class QIFDocumentType (*this, f, c);
    }

    QIFDocumentType& QIFDocumentType::
    operator= (const QIFDocumentType& x)
    {
      if (this != &x)
      {
        static_cast< ::xml_schema::type& > (*this) = x;
        this->QPId_ = x.QPId_;
        this->Attributes_ = x.Attributes_;
        this->VersionHistory_ = x.VersionHistory_;
        this->Version_ = x.Version_;
        this->Header_ = x.Header_;
        this->ValidationCounts_ = x.ValidationCounts_;
        this->ProductDataQuality_ = x.ProductDataQuality_;
        this->ExternalQIFReferences_ = x.ExternalQIFReferences_;
        this->StandardsDefinitions_ = x.StandardsDefinitions_;
        this->SoftwareDefinitions_ = x.SoftwareDefinitions_;
        this->AlgorithmDefinitions_ = x.AlgorithmDefinitions_;
        this->PreInspectionTraceability_ = x.PreInspectionTraceability_;
        this->FileUnits_ = x.FileUnits_;
        this->DatumDefinitions_ = x.DatumDefinitions_;
        this->DatumTargetDefinitions_ = x.DatumTargetDefinitions_;
        this->Transforms_ = x.Transforms_;
        this->CoordinateSystems_ = x.CoordinateSystems_;
        this->DatumReferenceFrames_ = x.DatumReferenceFrames_;
        this->MeasurementResources_ = x.MeasurementResources_;
        this->ThreadSpecifications_ = x.ThreadSpecifications_;
        this->Product_ = x.Product_;
        this->Features_ = x.Features_;
        this->FeatureZones_ = x.FeatureZones_;
        this->Characteristics_ = x.Characteristics_;
        this->Plan_ = x.Plan_;
        this->Results_ = x.Results_;
        this->Statistics_ = x.Statistics_;
        this->ManufacturingProcessTraceabilities_ = x.ManufacturingProcessTraceabilities_;
        this->Rules_ = x.Rules_;
        this->UserDataXML_ = x.UserDataXML_;
        this->Signature_ = x.Signature_;
        this->versionQIF_ = x.versionQIF_;
        this->idMax_ = x.idMax_;
      }

      return *this;
    }

    QIFDocumentType::
    ~QIFDocumentType ()
    {
    }

    // QIFDocumentHeaderType
    //

    QIFDocumentHeaderType::
    QIFDocumentHeaderType ()
    : ::xml_schema::type (),
      Application_ (this),
      Author_ (this),
      ApplicationSource_ (this),
      Description_ (this),
      Scope_ (this)
    {
    }

    QIFDocumentHeaderType::
    QIFDocumentHeaderType (const QIFDocumentHeaderType& x,
                           ::xml_schema::flags f,
                           ::xml_schema::container* c)
    : ::xml_schema::type (x, f, c),
      Application_ (x.Application_, f, this),
      Author_ (x.Author_, f, this),
      ApplicationSource_ (x.ApplicationSource_, f, this),
      Description_ (x.Description_, f, this),
      Scope_ (x.Scope_, f, this)
    {
    }

    QIFDocumentHeaderType::
    QIFDocumentHeaderType (const xercesc::DOMElement& e,
                           ::xml_schema::flags f,
                           ::xml_schema::container* c)
    : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
      Application_ (this),
      Author_ (this),
      ApplicationSource_ (this),
      Description_ (this),
      Scope_ (this)
    {
      if ((f & ::xml_schema::flags::base) == 0)
      {
        ::xsd::cxx::xml::dom::parser< wchar_t > p (e, true, false, false);
        this->parse (p, f);
      }
    }

    void QIFDocumentHeaderType::
    parse (::xsd::cxx::xml::dom::parser< wchar_t >& p,
           ::xml_schema::flags f)
    {
      for (; p.more_content (); p.next_content (false))
      {
        const xercesc::DOMElement& i (p.cur_element ());
        const ::xsd::cxx::xml::qualified_name< wchar_t > n (
          ::xsd::cxx::xml::dom::name< wchar_t > (i));

        // Application
        //
        if (n.name () == L"Application" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< Application_type > r (
            Application_traits::create (i, f, this));

          if (!this->Application_)
          {
            this->Application_.set (::std::move (r));
            continue;
          }
        }

        // Author
        //
        if (n.name () == L"Author" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< Author_type > r (
            Author_traits::create (i, f, this));

          if (!this->Author_)
          {
            this->Author_.set (::std::move (r));
            continue;
          }
        }

        // ApplicationSource
        //
        if (n.name () == L"ApplicationSource" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< ApplicationSource_type > r (
            ApplicationSource_traits::create (i, f, this));

          if (!this->ApplicationSource_)
          {
            this->ApplicationSource_.set (::std::move (r));
            continue;
          }
        }

        // Description
        //
        if (n.name () == L"Description" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< Description_type > r (
            Description_traits::create (i, f, this));

          if (!this->Description_)
          {
            this->Description_.set (::std::move (r));
            continue;
          }
        }

        // Scope
        //
        if (n.name () == L"Scope" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< Scope_type > r (
            Scope_traits::create (i, f, this));

          if (!this->Scope_)
          {
            this->Scope_.set (::std::move (r));
            continue;
          }
        }

        break;
      }
    }

    QIFDocumentHeaderType* QIFDocumentHeaderType::
    _clone (::xml_schema::flags f,
            ::xml_schema::container* c) const
    {
      return new class QIFDocumentHeaderType (*this, f, c);
    }

    QIFDocumentHeaderType& QIFDocumentHeaderType::
    operator= (const QIFDocumentHeaderType& x)
    {
      if (this != &x)
      {
        static_cast< ::xml_schema::type& > (*this) = x;
        this->Application_ = x.Application_;
        this->Author_ = x.Author_;
        this->ApplicationSource_ = x.ApplicationSource_;
        this->Description_ = x.Description_;
        this->Scope_ = x.Scope_;
      }

      return *this;
    }

    QIFDocumentHeaderType::
    ~QIFDocumentHeaderType ()
    {
    }

    // ExternalQIFReferencesType
    //

    ExternalQIFReferencesType::
    ExternalQIFReferencesType ()
    : ::xml_schema::type (),
      ExternalQIFDocument_ (this),
      n_ (this)
    {
    }

    ExternalQIFReferencesType::
    ExternalQIFReferencesType (const n_type& n)
    : ::xml_schema::type (),
      ExternalQIFDocument_ (this),
      n_ (n, this)
    {
    }

    ExternalQIFReferencesType::
    ExternalQIFReferencesType (const ExternalQIFReferencesType& x,
                               ::xml_schema::flags f,
                               ::xml_schema::container* c)
    : ::xml_schema::type (x, f, c),
      ExternalQIFDocument_ (x.ExternalQIFDocument_, f, this),
      n_ (x.n_, f, this)
    {
    }

    ExternalQIFReferencesType::
    ExternalQIFReferencesType (const xercesc::DOMElement& e,
                               ::xml_schema::flags f,
                               ::xml_schema::container* c)
    : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
      ExternalQIFDocument_ (this),
      n_ (this)
    {
      if ((f & ::xml_schema::flags::base) == 0)
      {
        ::xsd::cxx::xml::dom::parser< wchar_t > p (e, true, false, true);
        this->parse (p, f);
      }
    }

    void ExternalQIFReferencesType::
    parse (::xsd::cxx::xml::dom::parser< wchar_t >& p,
           ::xml_schema::flags f)
    {
      for (; p.more_content (); p.next_content (false))
      {
        const xercesc::DOMElement& i (p.cur_element ());
        const ::xsd::cxx::xml::qualified_name< wchar_t > n (
          ::xsd::cxx::xml::dom::name< wchar_t > (i));

        // ExternalQIFDocument
        //
        if (n.name () == L"ExternalQIFDocument" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< ExternalQIFDocument_type > r (
            ExternalQIFDocument_traits::create (i, f, this));

          this->ExternalQIFDocument_.push_back (::std::move (r));
          continue;
        }

        break;
      }

      while (p.more_attributes ())
      {
        const xercesc::DOMAttr& i (p.next_attribute ());
        const ::xsd::cxx::xml::qualified_name< wchar_t > n (
          ::xsd::cxx::xml::dom::name< wchar_t > (i));

        if (n.name () == L"n" && n.namespace_ ().empty ())
        {
          this->n_.set (n_traits::create (i, f, this));
          continue;
        }
      }

      if (!n_.present ())
      {
        throw ::xsd::cxx::tree::expected_attribute< wchar_t > (
          L"n",
          L"");
      }
    }

    ExternalQIFReferencesType* ExternalQIFReferencesType::
    _clone (::xml_schema::flags f,
            ::xml_schema::container* c) const
    {
      return new class ExternalQIFReferencesType (*this, f, c);
    }

    ExternalQIFReferencesType& ExternalQIFReferencesType::
    operator= (const ExternalQIFReferencesType& x)
    {
      if (this != &x)
      {
        static_cast< ::xml_schema::type& > (*this) = x;
        this->ExternalQIFDocument_ = x.ExternalQIFDocument_;
        this->n_ = x.n_;
      }

      return *this;
    }

    ExternalQIFReferencesType::
    ~ExternalQIFReferencesType ()
    {
    }

    // ExternalQIFDocumentReferenceType
    //

    ExternalQIFDocumentReferenceType::
    ExternalQIFDocumentReferenceType ()
    : ::xml_schema::type (),
      QPId_ (this),
      URI_ (this),
      Description_ (this),
      id_ (this)
    {
    }

    ExternalQIFDocumentReferenceType::
    ExternalQIFDocumentReferenceType (const QPId_type& QPId,
                                      const id_type& id)
    : ::xml_schema::type (),
      QPId_ (QPId, this),
      URI_ (this),
      Description_ (this),
      id_ (id, this)
    {
    }

    ExternalQIFDocumentReferenceType::
    ExternalQIFDocumentReferenceType (const ExternalQIFDocumentReferenceType& x,
                                      ::xml_schema::flags f,
                                      ::xml_schema::container* c)
    : ::xml_schema::type (x, f, c),
      QPId_ (x.QPId_, f, this),
      URI_ (x.URI_, f, this),
      Description_ (x.Description_, f, this),
      id_ (x.id_, f, this)
    {
    }

    ExternalQIFDocumentReferenceType::
    ExternalQIFDocumentReferenceType (const xercesc::DOMElement& e,
                                      ::xml_schema::flags f,
                                      ::xml_schema::container* c)
    : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
      QPId_ (this),
      URI_ (this),
      Description_ (this),
      id_ (this)
    {
      if ((f & ::xml_schema::flags::base) == 0)
      {
        ::xsd::cxx::xml::dom::parser< wchar_t > p (e, true, false, true);
        this->parse (p, f);
      }
    }

    void ExternalQIFDocumentReferenceType::
    parse (::xsd::cxx::xml::dom::parser< wchar_t >& p,
           ::xml_schema::flags f)
    {
      for (; p.more_content (); p.next_content (false))
      {
        const xercesc::DOMElement& i (p.cur_element ());
        const ::xsd::cxx::xml::qualified_name< wchar_t > n (
          ::xsd::cxx::xml::dom::name< wchar_t > (i));

        // QPId
        //
        if (n.name () == L"QPId" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< QPId_type > r (
            QPId_traits::create (i, f, this));

          if (!QPId_.present ())
          {
            this->QPId_.set (::std::move (r));
            continue;
          }
        }

        // URI
        //
        if (n.name () == L"URI" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< URI_type > r (
            URI_traits::create (i, f, this));

          if (!this->URI_)
          {
            this->URI_.set (::std::move (r));
            continue;
          }
        }

        // Description
        //
        if (n.name () == L"Description" && n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
        {
          ::std::unique_ptr< Description_type > r (
            Description_traits::create (i, f, this));

          if (!this->Description_)
          {
            this->Description_.set (::std::move (r));
            continue;
          }
        }

        break;
      }

      if (!QPId_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< wchar_t > (
          L"QPId",
          L"http://qifstandards.org/xsd/qif3");
      }

      while (p.more_attributes ())
      {
        const xercesc::DOMAttr& i (p.next_attribute ());
        const ::xsd::cxx::xml::qualified_name< wchar_t > n (
          ::xsd::cxx::xml::dom::name< wchar_t > (i));

        if (n.name () == L"id" && n.namespace_ ().empty ())
        {
          this->id_.set (id_traits::create (i, f, this));
          continue;
        }
      }

      if (!id_.present ())
      {
        throw ::xsd::cxx::tree::expected_attribute< wchar_t > (
          L"id",
          L"");
      }
    }

    ExternalQIFDocumentReferenceType* ExternalQIFDocumentReferenceType::
    _clone (::xml_schema::flags f,
            ::xml_schema::container* c) const
    {
      return new class ExternalQIFDocumentReferenceType (*this, f, c);
    }

    ExternalQIFDocumentReferenceType& ExternalQIFDocumentReferenceType::
    operator= (const ExternalQIFDocumentReferenceType& x)
    {
      if (this != &x)
      {
        static_cast< ::xml_schema::type& > (*this) = x;
        this->QPId_ = x.QPId_;
        this->URI_ = x.URI_;
        this->Description_ = x.Description_;
        this->id_ = x.id_;
      }

      return *this;
    }

    ExternalQIFDocumentReferenceType::
    ~ExternalQIFDocumentReferenceType ()
    {
    }
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace xsd
{
  namespace qif30
  {
    ::std::unique_ptr< ::xsd::qif30::QIFDocumentType >
    QIFDocument (const ::std::wstring& u,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::flags::dont_initialize) == 0,
        (f & ::xml_schema::flags::keep_dom) == 0);

      ::xsd::cxx::tree::error_handler< wchar_t > h;

      ::xml_schema::dom::unique_ptr< xercesc::DOMDocument > d (
        ::xsd::cxx::xml::dom::parse< wchar_t > (
          u, h, p, f));

      h.throw_if_failed< ::xsd::cxx::tree::parsing< wchar_t > > ();

      return ::std::unique_ptr< ::xsd::qif30::QIFDocumentType > (
        ::xsd::qif30::QIFDocument (
          std::move (d), f | ::xml_schema::flags::own_dom, p));
    }

    ::std::unique_ptr< ::xsd::qif30::QIFDocumentType >
    QIFDocument (const ::std::wstring& u,
                 ::xml_schema::error_handler& h,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::flags::dont_initialize) == 0,
        (f & ::xml_schema::flags::keep_dom) == 0);

      ::xml_schema::dom::unique_ptr< xercesc::DOMDocument > d (
        ::xsd::cxx::xml::dom::parse< wchar_t > (
          u, h, p, f));

      if (!d.get ())
        throw ::xsd::cxx::tree::parsing< wchar_t > ();

      return ::std::unique_ptr< ::xsd::qif30::QIFDocumentType > (
        ::xsd::qif30::QIFDocument (
          std::move (d), f | ::xml_schema::flags::own_dom, p));
    }

    ::std::unique_ptr< ::xsd::qif30::QIFDocumentType >
    QIFDocument (const ::std::wstring& u,
                 xercesc::DOMErrorHandler& h,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
    {
      ::xml_schema::dom::unique_ptr< xercesc::DOMDocument > d (
        ::xsd::cxx::xml::dom::parse< wchar_t > (
          u, h, p, f));

      if (!d.get ())
        throw ::xsd::cxx::tree::parsing< wchar_t > ();

      return ::std::unique_ptr< ::xsd::qif30::QIFDocumentType > (
        ::xsd::qif30::QIFDocument (
          std::move (d), f | ::xml_schema::flags::own_dom, p));
    }

    ::std::unique_ptr< ::xsd::qif30::QIFDocumentType >
    QIFDocument (::std::istream& is,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::flags::dont_initialize) == 0,
        (f & ::xml_schema::flags::keep_dom) == 0);

      ::xsd::cxx::xml::sax::std_input_source isrc (is);
      return ::xsd::qif30::QIFDocument (isrc, f, p);
    }

    ::std::unique_ptr< ::xsd::qif30::QIFDocumentType >
    QIFDocument (::std::istream& is,
                 ::xml_schema::error_handler& h,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::flags::dont_initialize) == 0,
        (f & ::xml_schema::flags::keep_dom) == 0);

      ::xsd::cxx::xml::sax::std_input_source isrc (is);
      return ::xsd::qif30::QIFDocument (isrc, h, f, p);
    }

    ::std::unique_ptr< ::xsd::qif30::QIFDocumentType >
    QIFDocument (::std::istream& is,
                 xercesc::DOMErrorHandler& h,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
    {
      ::xsd::cxx::xml::sax::std_input_source isrc (is);
      return ::xsd::qif30::QIFDocument (isrc, h, f, p);
    }

    ::std::unique_ptr< ::xsd::qif30::QIFDocumentType >
    QIFDocument (::std::istream& is,
                 const ::std::wstring& sid,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::flags::dont_initialize) == 0,
        (f & ::xml_schema::flags::keep_dom) == 0);

      ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
      return ::xsd::qif30::QIFDocument (isrc, f, p);
    }

    ::std::unique_ptr< ::xsd::qif30::QIFDocumentType >
    QIFDocument (::std::istream& is,
                 const ::std::wstring& sid,
                 ::xml_schema::error_handler& h,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::flags::dont_initialize) == 0,
        (f & ::xml_schema::flags::keep_dom) == 0);

      ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
      return ::xsd::qif30::QIFDocument (isrc, h, f, p);
    }

    ::std::unique_ptr< ::xsd::qif30::QIFDocumentType >
    QIFDocument (::std::istream& is,
                 const ::std::wstring& sid,
                 xercesc::DOMErrorHandler& h,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
    {
      ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
      return ::xsd::qif30::QIFDocument (isrc, h, f, p);
    }

    ::std::unique_ptr< ::xsd::qif30::QIFDocumentType >
    QIFDocument (xercesc::InputSource& i,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
    {
      ::xsd::cxx::tree::error_handler< wchar_t > h;

      ::xml_schema::dom::unique_ptr< xercesc::DOMDocument > d (
        ::xsd::cxx::xml::dom::parse< wchar_t > (
          i, h, p, f));

      h.throw_if_failed< ::xsd::cxx::tree::parsing< wchar_t > > ();

      return ::std::unique_ptr< ::xsd::qif30::QIFDocumentType > (
        ::xsd::qif30::QIFDocument (
          std::move (d), f | ::xml_schema::flags::own_dom, p));
    }

    ::std::unique_ptr< ::xsd::qif30::QIFDocumentType >
    QIFDocument (xercesc::InputSource& i,
                 ::xml_schema::error_handler& h,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
    {
      ::xml_schema::dom::unique_ptr< xercesc::DOMDocument > d (
        ::xsd::cxx::xml::dom::parse< wchar_t > (
          i, h, p, f));

      if (!d.get ())
        throw ::xsd::cxx::tree::parsing< wchar_t > ();

      return ::std::unique_ptr< ::xsd::qif30::QIFDocumentType > (
        ::xsd::qif30::QIFDocument (
          std::move (d), f | ::xml_schema::flags::own_dom, p));
    }

    ::std::unique_ptr< ::xsd::qif30::QIFDocumentType >
    QIFDocument (xercesc::InputSource& i,
                 xercesc::DOMErrorHandler& h,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
    {
      ::xml_schema::dom::unique_ptr< xercesc::DOMDocument > d (
        ::xsd::cxx::xml::dom::parse< wchar_t > (
          i, h, p, f));

      if (!d.get ())
        throw ::xsd::cxx::tree::parsing< wchar_t > ();

      return ::std::unique_ptr< ::xsd::qif30::QIFDocumentType > (
        ::xsd::qif30::QIFDocument (
          std::move (d), f | ::xml_schema::flags::own_dom, p));
    }

    ::std::unique_ptr< ::xsd::qif30::QIFDocumentType >
    QIFDocument (const xercesc::DOMDocument& doc,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
    {
      if (f & ::xml_schema::flags::keep_dom)
      {
        ::xml_schema::dom::unique_ptr< xercesc::DOMDocument > d (
          static_cast< xercesc::DOMDocument* > (doc.cloneNode (true)));

        return ::std::unique_ptr< ::xsd::qif30::QIFDocumentType > (
          ::xsd::qif30::QIFDocument (
            std::move (d), f | ::xml_schema::flags::own_dom, p));
      }

      const xercesc::DOMElement& e (*doc.getDocumentElement ());
      const ::xsd::cxx::xml::qualified_name< wchar_t > n (
        ::xsd::cxx::xml::dom::name< wchar_t > (e));

      if (n.name () == L"QIFDocument" &&
          n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
      {
        ::std::unique_ptr< ::xsd::qif30::QIFDocumentType > r (
          ::xsd::cxx::tree::traits< ::xsd::qif30::QIFDocumentType, wchar_t >::create (
            e, f, 0));
        return r;
      }

      throw ::xsd::cxx::tree::unexpected_element < wchar_t > (
        n.name (),
        n.namespace_ (),
        L"QIFDocument",
        L"http://qifstandards.org/xsd/qif3");
    }

    ::std::unique_ptr< ::xsd::qif30::QIFDocumentType >
    QIFDocument (::xml_schema::dom::unique_ptr< xercesc::DOMDocument > d,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties&)
    {
      ::xml_schema::dom::unique_ptr< xercesc::DOMDocument > c (
        ((f & ::xml_schema::flags::keep_dom) &&
         !(f & ::xml_schema::flags::own_dom))
        ? static_cast< xercesc::DOMDocument* > (d->cloneNode (true))
        : 0);

      xercesc::DOMDocument& doc (c.get () ? *c : *d);
      const xercesc::DOMElement& e (*doc.getDocumentElement ());

      const ::xsd::cxx::xml::qualified_name< wchar_t > n (
        ::xsd::cxx::xml::dom::name< wchar_t > (e));

      if (f & ::xml_schema::flags::keep_dom)
        doc.setUserData (::xml_schema::dom::tree_node_key,
                         (c.get () ? &c : &d),
                         0);

      if (n.name () == L"QIFDocument" &&
          n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
      {
        ::std::unique_ptr< ::xsd::qif30::QIFDocumentType > r (
          ::xsd::cxx::tree::traits< ::xsd::qif30::QIFDocumentType, wchar_t >::create (
            e, f, 0));
        return r;
      }

      throw ::xsd::cxx::tree::unexpected_element < wchar_t > (
        n.name (),
        n.namespace_ (),
        L"QIFDocument",
        L"http://qifstandards.org/xsd/qif3");
    }
  }
}

#include <ostream>
#include <xsd/cxx/tree/error-handler.hxx>
#include <xsd/cxx/xml/dom/serialization-source.hxx>

#include <xsd/cxx/tree/type-serializer-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_serializer_plate< 0, wchar_t >
  type_serializer_plate_init;
}

namespace xsd
{
  namespace qif30
  {
    void
    QIFDocument (::std::ostream& o,
                 const ::xsd::qif30::QIFDocumentType& s,
                 const ::xml_schema::namespace_infomap& m,
                 const ::std::wstring& e,
                 ::xml_schema::flags f)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::flags::dont_initialize) == 0);

      ::xml_schema::dom::unique_ptr< xercesc::DOMDocument > d (
        ::xsd::qif30::QIFDocument (s, m, f));

      ::xsd::cxx::tree::error_handler< wchar_t > h;

      ::xsd::cxx::xml::dom::ostream_format_target t (o);
      if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
      {
        h.throw_if_failed< ::xsd::cxx::tree::serialization< wchar_t > > ();
      }
    }

    void
    QIFDocument (::std::ostream& o,
                 const ::xsd::qif30::QIFDocumentType& s,
                 ::xml_schema::error_handler& h,
                 const ::xml_schema::namespace_infomap& m,
                 const ::std::wstring& e,
                 ::xml_schema::flags f)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::flags::dont_initialize) == 0);

      ::xml_schema::dom::unique_ptr< xercesc::DOMDocument > d (
        ::xsd::qif30::QIFDocument (s, m, f));
      ::xsd::cxx::xml::dom::ostream_format_target t (o);
      if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
      {
        throw ::xsd::cxx::tree::serialization< wchar_t > ();
      }
    }

    void
    QIFDocument (::std::ostream& o,
                 const ::xsd::qif30::QIFDocumentType& s,
                 xercesc::DOMErrorHandler& h,
                 const ::xml_schema::namespace_infomap& m,
                 const ::std::wstring& e,
                 ::xml_schema::flags f)
    {
      ::xml_schema::dom::unique_ptr< xercesc::DOMDocument > d (
        ::xsd::qif30::QIFDocument (s, m, f));
      ::xsd::cxx::xml::dom::ostream_format_target t (o);
      if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
      {
        throw ::xsd::cxx::tree::serialization< wchar_t > ();
      }
    }

    void
    QIFDocument (xercesc::XMLFormatTarget& t,
                 const ::xsd::qif30::QIFDocumentType& s,
                 const ::xml_schema::namespace_infomap& m,
                 const ::std::wstring& e,
                 ::xml_schema::flags f)
    {
      ::xml_schema::dom::unique_ptr< xercesc::DOMDocument > d (
        ::xsd::qif30::QIFDocument (s, m, f));

      ::xsd::cxx::tree::error_handler< wchar_t > h;

      if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
      {
        h.throw_if_failed< ::xsd::cxx::tree::serialization< wchar_t > > ();
      }
    }

    void
    QIFDocument (xercesc::XMLFormatTarget& t,
                 const ::xsd::qif30::QIFDocumentType& s,
                 ::xml_schema::error_handler& h,
                 const ::xml_schema::namespace_infomap& m,
                 const ::std::wstring& e,
                 ::xml_schema::flags f)
    {
      ::xml_schema::dom::unique_ptr< xercesc::DOMDocument > d (
        ::xsd::qif30::QIFDocument (s, m, f));
      if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
      {
        throw ::xsd::cxx::tree::serialization< wchar_t > ();
      }
    }

    void
    QIFDocument (xercesc::XMLFormatTarget& t,
                 const ::xsd::qif30::QIFDocumentType& s,
                 xercesc::DOMErrorHandler& h,
                 const ::xml_schema::namespace_infomap& m,
                 const ::std::wstring& e,
                 ::xml_schema::flags f)
    {
      ::xml_schema::dom::unique_ptr< xercesc::DOMDocument > d (
        ::xsd::qif30::QIFDocument (s, m, f));
      if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
      {
        throw ::xsd::cxx::tree::serialization< wchar_t > ();
      }
    }

    void
    QIFDocument (xercesc::DOMDocument& d,
                 const ::xsd::qif30::QIFDocumentType& s,
                 ::xml_schema::flags)
    {
      xercesc::DOMElement& e (*d.getDocumentElement ());
      const ::xsd::cxx::xml::qualified_name< wchar_t > n (
        ::xsd::cxx::xml::dom::name< wchar_t > (e));

      if (n.name () == L"QIFDocument" &&
          n.namespace_ () == L"http://qifstandards.org/xsd/qif3")
      {
        e << s;
      }
      else
      {
        throw ::xsd::cxx::tree::unexpected_element < wchar_t > (
          n.name (),
          n.namespace_ (),
          L"QIFDocument",
          L"http://qifstandards.org/xsd/qif3");
      }
    }

    ::xml_schema::dom::unique_ptr< xercesc::DOMDocument >
    QIFDocument (const ::xsd::qif30::QIFDocumentType& s,
                 const ::xml_schema::namespace_infomap& m,
                 ::xml_schema::flags f)
    {
      ::xml_schema::dom::unique_ptr< xercesc::DOMDocument > d (
        ::xsd::cxx::xml::dom::serialize< wchar_t > (
          L"QIFDocument",
          L"http://qifstandards.org/xsd/qif3",
          m, f));

      ::xsd::qif30::QIFDocument (*d, s, f);
      return d;
    }

    void
    operator<< (xercesc::DOMElement& e, const QIFDocumentType& i)
    {
      e << static_cast< const ::xml_schema::type& > (i);

      // QPId
      //
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"QPId",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << i.QPId ();
      }

      // Attributes
      //
      if (i.Attributes ())
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"Attributes",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << *i.Attributes ();
      }

      // VersionHistory
      //
      if (i.VersionHistory ())
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"VersionHistory",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << *i.VersionHistory ();
      }

      // Version
      //
      if (i.Version ())
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"Version",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << *i.Version ();
      }

      // Header
      //
      if (i.Header ())
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"Header",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << *i.Header ();
      }

      // ValidationCounts
      //
      if (i.ValidationCounts ())
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"ValidationCounts",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << *i.ValidationCounts ();
      }

      // ProductDataQuality
      //
      if (i.ProductDataQuality ())
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"ProductDataQuality",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << *i.ProductDataQuality ();
      }

      // ExternalQIFReferences
      //
      if (i.ExternalQIFReferences ())
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"ExternalQIFReferences",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << *i.ExternalQIFReferences ();
      }

      // StandardsDefinitions
      //
      if (i.StandardsDefinitions ())
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"StandardsDefinitions",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << *i.StandardsDefinitions ();
      }

      // SoftwareDefinitions
      //
      if (i.SoftwareDefinitions ())
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"SoftwareDefinitions",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << *i.SoftwareDefinitions ();
      }

      // AlgorithmDefinitions
      //
      if (i.AlgorithmDefinitions ())
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"AlgorithmDefinitions",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << *i.AlgorithmDefinitions ();
      }

      // PreInspectionTraceability
      //
      if (i.PreInspectionTraceability ())
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"PreInspectionTraceability",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << *i.PreInspectionTraceability ();
      }

      // FileUnits
      //
      if (i.FileUnits ())
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"FileUnits",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << *i.FileUnits ();
      }

      // DatumDefinitions
      //
      if (i.DatumDefinitions ())
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"DatumDefinitions",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << *i.DatumDefinitions ();
      }

      // DatumTargetDefinitions
      //
      if (i.DatumTargetDefinitions ())
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"DatumTargetDefinitions",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << *i.DatumTargetDefinitions ();
      }

      // Transforms
      //
      if (i.Transforms ())
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"Transforms",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << *i.Transforms ();
      }

      // CoordinateSystems
      //
      if (i.CoordinateSystems ())
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"CoordinateSystems",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << *i.CoordinateSystems ();
      }

      // DatumReferenceFrames
      //
      if (i.DatumReferenceFrames ())
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"DatumReferenceFrames",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << *i.DatumReferenceFrames ();
      }

      // MeasurementResources
      //
      if (i.MeasurementResources ())
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"MeasurementResources",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << *i.MeasurementResources ();
      }

      // ThreadSpecifications
      //
      if (i.ThreadSpecifications ())
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"ThreadSpecifications",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << *i.ThreadSpecifications ();
      }

      // Product
      //
      if (i.Product ())
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"Product",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << *i.Product ();
      }

      // Features
      //
      if (i.Features ())
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"Features",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << *i.Features ();
      }

      // FeatureZones
      //
      if (i.FeatureZones ())
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"FeatureZones",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << *i.FeatureZones ();
      }

      // Characteristics
      //
      if (i.Characteristics ())
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"Characteristics",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << *i.Characteristics ();
      }

      // Plan
      //
      if (i.Plan ())
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"Plan",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << *i.Plan ();
      }

      // Results
      //
      if (i.Results ())
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"Results",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << *i.Results ();
      }

      // Statistics
      //
      if (i.Statistics ())
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"Statistics",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << *i.Statistics ();
      }

      // ManufacturingProcessTraceabilities
      //
      if (i.ManufacturingProcessTraceabilities ())
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"ManufacturingProcessTraceabilities",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << *i.ManufacturingProcessTraceabilities ();
      }

      // Rules
      //
      if (i.Rules ())
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"Rules",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << *i.Rules ();
      }

      // UserDataXML
      //
      if (i.UserDataXML ())
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"UserDataXML",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << *i.UserDataXML ();
      }

      // Signature
      //
      if (i.Signature ())
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"Signature",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << *i.Signature ();
      }

      // versionQIF
      //
      {
        xercesc::DOMAttr& a (
          ::xsd::cxx::xml::dom::create_attribute (
            L"versionQIF",
            e));

        a << i.versionQIF ();
      }

      // idMax
      //
      {
        xercesc::DOMAttr& a (
          ::xsd::cxx::xml::dom::create_attribute (
            L"idMax",
            e));

        a << i.idMax ();
      }
    }

    void
    operator<< (xercesc::DOMElement& e, const QIFDocumentHeaderType& i)
    {
      e << static_cast< const ::xml_schema::type& > (i);

      // Application
      //
      if (i.Application ())
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"Application",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << *i.Application ();
      }

      // Author
      //
      if (i.Author ())
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"Author",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << *i.Author ();
      }

      // ApplicationSource
      //
      if (i.ApplicationSource ())
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"ApplicationSource",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << *i.ApplicationSource ();
      }

      // Description
      //
      if (i.Description ())
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"Description",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << *i.Description ();
      }

      // Scope
      //
      if (i.Scope ())
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"Scope",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << *i.Scope ();
      }
    }

    void
    operator<< (xercesc::DOMElement& e, const ExternalQIFReferencesType& i)
    {
      e << static_cast< const ::xml_schema::type& > (i);

      // ExternalQIFDocument
      //
      for (ExternalQIFReferencesType::ExternalQIFDocument_const_iterator
           b (i.ExternalQIFDocument ().begin ()), n (i.ExternalQIFDocument ().end ());
           b != n; ++b)
      {
        const ExternalQIFReferencesType::ExternalQIFDocument_type& x (*b);

        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"ExternalQIFDocument",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << x;
      }

      // n
      //
      {
        xercesc::DOMAttr& a (
          ::xsd::cxx::xml::dom::create_attribute (
            L"n",
            e));

        a << i.n ();
      }
    }

    void
    operator<< (xercesc::DOMElement& e, const ExternalQIFDocumentReferenceType& i)
    {
      e << static_cast< const ::xml_schema::type& > (i);

      // QPId
      //
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"QPId",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << i.QPId ();
      }

      // URI
      //
      if (i.URI ())
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"URI",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << *i.URI ();
      }

      // Description
      //
      if (i.Description ())
      {
        xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            L"Description",
            L"http://qifstandards.org/xsd/qif3",
            e));

        s << *i.Description ();
      }

      // id
      //
      {
        xercesc::DOMAttr& a (
          ::xsd::cxx::xml::dom::create_attribute (
            L"id",
            e));

        a << i.id ();
      }
    }
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

