// Copyright (c) 2005-2023 Code Synthesis.
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis gives permission
// to link this program with the Xerces-C++ library (or with modified
// versions of Xerces-C++ that use the same license as Xerces-C++), and
// distribute linked combinations including the two. You must obey the GNU
// General Public License version 2 in all respects for all of the code
// used other than Xerces-C++. If you modify this copy of the program, you
// may extend this exception to your version of the program, but you are
// not obligated to do so. If you do not wish to do so, delete this
// exception statement from your version.
//
// Furthermore, Code Synthesis makes a special exception for the Free/Libre
// and Open Source Software (FLOSS) which is described in the accompanying
// FLOSSE file.
//

#ifndef CXX___QIFAPPLICATIONS_QIFDOCUMENT_HXX
#define CXX___QIFAPPLICATIONS_QIFDOCUMENT_HXX

#ifndef XSD_CXX11
#define XSD_CXX11
#endif

#ifndef XSD_USE_WCHAR
#define XSD_USE_WCHAR
#endif

#ifndef XSD_CXX_TREE_USE_WCHAR
#define XSD_CXX_TREE_USE_WCHAR
#endif

// Begin prologue.
//
#include "..\\export.hxx"
//
// End prologue.

#include <xsd/cxx/config.hxx>

#if (LIBXSD_VERSION != 400002000000000L)
#error XSD runtime version mismatch
#endif

#include <xsd/cxx/pre.hxx>

#include <xsd/cxx/tree/exceptions.hxx>
#include <xsd/cxx/tree/elements.hxx>
#include <xsd/cxx/tree/types.hxx>

#include <xsd/cxx/xml/error-handler.hxx>

#include <xsd/cxx/xml/dom/auto-ptr.hxx>

#include <xsd/cxx/tree/parsing.hxx>
#include <xsd/cxx/tree/parsing/byte.hxx>
#include <xsd/cxx/tree/parsing/unsigned-byte.hxx>
#include <xsd/cxx/tree/parsing/short.hxx>
#include <xsd/cxx/tree/parsing/unsigned-short.hxx>
#include <xsd/cxx/tree/parsing/int.hxx>
#include <xsd/cxx/tree/parsing/unsigned-int.hxx>
#include <xsd/cxx/tree/parsing/long.hxx>
#include <xsd/cxx/tree/parsing/unsigned-long.hxx>
#include <xsd/cxx/tree/parsing/boolean.hxx>
#include <xsd/cxx/tree/parsing/float.hxx>
#include <xsd/cxx/tree/parsing/double.hxx>
#include <xsd/cxx/tree/parsing/decimal.hxx>

#include <xsd/cxx/xml/dom/serialization-header.hxx>
#include <xsd/cxx/tree/serialization.hxx>
#include <xsd/cxx/tree/serialization/byte.hxx>
#include <xsd/cxx/tree/serialization/unsigned-byte.hxx>
#include <xsd/cxx/tree/serialization/short.hxx>
#include <xsd/cxx/tree/serialization/unsigned-short.hxx>
#include <xsd/cxx/tree/serialization/int.hxx>
#include <xsd/cxx/tree/serialization/unsigned-int.hxx>
#include <xsd/cxx/tree/serialization/long.hxx>
#include <xsd/cxx/tree/serialization/unsigned-long.hxx>
#include <xsd/cxx/tree/serialization/boolean.hxx>
#include <xsd/cxx/tree/serialization/float.hxx>
#include <xsd/cxx/tree/serialization/double.hxx>
#include <xsd/cxx/tree/serialization/decimal.hxx>

namespace xml_schema
{
  // anyType and anySimpleType.
  //
  typedef ::xsd::cxx::tree::type type;
  typedef ::xsd::cxx::tree::simple_type< wchar_t, type > simple_type;
  typedef ::xsd::cxx::tree::type container;

  // 8-bit
  //
  typedef signed char byte;
  typedef unsigned char unsigned_byte;

  // 16-bit
  //
  typedef short short_;
  typedef unsigned short unsigned_short;

  // 32-bit
  //
  typedef int int_;
  typedef unsigned int unsigned_int;

  // 64-bit
  //
  typedef long long long_;
  typedef unsigned long long unsigned_long;

  // Supposed to be arbitrary-length integral types.
  //
  typedef long long integer;
  typedef long long non_positive_integer;
  typedef unsigned long long non_negative_integer;
  typedef unsigned long long positive_integer;
  typedef long long negative_integer;

  // Boolean.
  //
  typedef bool boolean;

  // Floating-point types.
  //
  typedef float float_;
  typedef double double_;
  typedef double decimal;

  // String types.
  //
  typedef ::xsd::cxx::tree::string< wchar_t, simple_type > string;
  typedef ::xsd::cxx::tree::normalized_string< wchar_t, string > normalized_string;
  typedef ::xsd::cxx::tree::token< wchar_t, normalized_string > token;
  typedef ::xsd::cxx::tree::name< wchar_t, token > name;
  typedef ::xsd::cxx::tree::nmtoken< wchar_t, token > nmtoken;
  typedef ::xsd::cxx::tree::nmtokens< wchar_t, simple_type, nmtoken > nmtokens;
  typedef ::xsd::cxx::tree::ncname< wchar_t, name > ncname;
  typedef ::xsd::cxx::tree::language< wchar_t, token > language;

  // ID/IDREF.
  //
  typedef ::xsd::cxx::tree::id< wchar_t, ncname > id;
  typedef ::xsd::cxx::tree::idref< wchar_t, ncname, type > idref;
  typedef ::xsd::cxx::tree::idrefs< wchar_t, simple_type, idref > idrefs;

  // URI.
  //
  typedef ::xsd::cxx::tree::uri< wchar_t, simple_type > uri;

  // Qualified name.
  //
  typedef ::xsd::cxx::tree::qname< wchar_t, simple_type, uri, ncname > qname;

  // Binary.
  //
  typedef ::xsd::cxx::tree::buffer< wchar_t > buffer;
  typedef ::xsd::cxx::tree::base64_binary< wchar_t, simple_type > base64_binary;
  typedef ::xsd::cxx::tree::hex_binary< wchar_t, simple_type > hex_binary;

  // Date/time.
  //
  typedef ::xsd::cxx::tree::time_zone time_zone;
  typedef ::xsd::cxx::tree::date< wchar_t, simple_type > date;
  typedef ::xsd::cxx::tree::date_time< wchar_t, simple_type > date_time;
  typedef ::xsd::cxx::tree::duration< wchar_t, simple_type > duration;
  typedef ::xsd::cxx::tree::gday< wchar_t, simple_type > gday;
  typedef ::xsd::cxx::tree::gmonth< wchar_t, simple_type > gmonth;
  typedef ::xsd::cxx::tree::gmonth_day< wchar_t, simple_type > gmonth_day;
  typedef ::xsd::cxx::tree::gyear< wchar_t, simple_type > gyear;
  typedef ::xsd::cxx::tree::gyear_month< wchar_t, simple_type > gyear_month;
  typedef ::xsd::cxx::tree::time< wchar_t, simple_type > time;

  // Entity.
  //
  typedef ::xsd::cxx::tree::entity< wchar_t, ncname > entity;
  typedef ::xsd::cxx::tree::entities< wchar_t, simple_type, entity > entities;

  typedef ::xsd::cxx::tree::content_order content_order;
  // Namespace information and list stream. Used in
  // serialization functions.
  //
  typedef ::xsd::cxx::xml::dom::namespace_info< wchar_t > namespace_info;
  typedef ::xsd::cxx::xml::dom::namespace_infomap< wchar_t > namespace_infomap;
  typedef ::xsd::cxx::tree::list_stream< wchar_t > list_stream;
  typedef ::xsd::cxx::tree::as_double< double_ > as_double;
  typedef ::xsd::cxx::tree::as_decimal< decimal > as_decimal;
  typedef ::xsd::cxx::tree::facet facet;

  // Flags and properties.
  //
  typedef ::xsd::cxx::tree::flags flags;
  typedef ::xsd::cxx::tree::properties< wchar_t > properties;

  // Parsing/serialization diagnostics.
  //
  typedef ::xsd::cxx::tree::severity severity;
  typedef ::xsd::cxx::tree::error< wchar_t > error;
  typedef ::xsd::cxx::tree::diagnostics< wchar_t > diagnostics;

  // Exceptions.
  //
  typedef ::xsd::cxx::tree::exception< wchar_t > exception;
  typedef ::xsd::cxx::tree::bounds< wchar_t > bounds;
  typedef ::xsd::cxx::tree::duplicate_id< wchar_t > duplicate_id;
  typedef ::xsd::cxx::tree::parsing< wchar_t > parsing;
  typedef ::xsd::cxx::tree::expected_element< wchar_t > expected_element;
  typedef ::xsd::cxx::tree::unexpected_element< wchar_t > unexpected_element;
  typedef ::xsd::cxx::tree::expected_attribute< wchar_t > expected_attribute;
  typedef ::xsd::cxx::tree::unexpected_enumerator< wchar_t > unexpected_enumerator;
  typedef ::xsd::cxx::tree::expected_text_content< wchar_t > expected_text_content;
  typedef ::xsd::cxx::tree::no_prefix_mapping< wchar_t > no_prefix_mapping;
  typedef ::xsd::cxx::tree::no_type_info< wchar_t > no_type_info;
  typedef ::xsd::cxx::tree::not_derived< wchar_t > not_derived;
  typedef ::xsd::cxx::tree::serialization< wchar_t > serialization;

  // Error handler callback interface.
  //
  typedef ::xsd::cxx::xml::error_handler< wchar_t > error_handler;

  // DOM interaction.
  //
  namespace dom
  {
    // Automatic pointer for DOMDocument.
    //
    using ::xsd::cxx::xml::dom::unique_ptr;

#ifndef XSD_CXX_TREE_TREE_NODE_KEY__XML_SCHEMA
#define XSD_CXX_TREE_TREE_NODE_KEY__XML_SCHEMA
    // DOM user data key for back pointers to tree nodes.
    //
    const XMLCh* const tree_node_key = ::xsd::cxx::tree::user_data_keys::node;
#endif
  }
}

// Forward declarations.
//
namespace xsd
{
  namespace qif30
  {
    class QIFDocumentType;
    class QIFDocumentHeaderType;
    class ExternalQIFReferencesType;
    class ExternalQIFDocumentReferenceType;
  }
}


#include <memory>    // ::std::unique_ptr
#include <limits>    // std::numeric_limits
#include <algorithm> // std::binary_search
#include <utility>   // std::move

#include <xsd/cxx/tree/exceptions.hxx>
#include <xsd/cxx/tree/elements.hxx>
#include <xsd/cxx/tree/containers.hxx>
#include <xsd/cxx/tree/list.hxx>

#include <xsd/cxx/xml/dom/parsing-header.hxx>

#include "../QIFLibrary/xmldsig-core-schema-qif3-namespace.hxx"

#include "QIFPlan.hxx"

#include "QIFResults.hxx"

#include "QIFStatistics.hxx"

#include "QIFRules.hxx"

#include "QIFProduct.hxx"

#include "QIFMeasurementResources.hxx"

namespace xsd
{
  namespace qif30
  {
    class QIF30_SYMBOL_DECL QIFDocumentType: public ::xml_schema::type
    {
      public:
      // QPId
      //
      typedef ::xsd::qif30::QPIdType QPId_type;
      typedef ::xsd::cxx::tree::traits< QPId_type, wchar_t > QPId_traits;

      const QPId_type&
      QPId () const;

      QPId_type&
      QPId ();

      void
      QPId (const QPId_type& x);

      void
      QPId (::std::unique_ptr< QPId_type > p);

      // Attributes
      //
      typedef ::xsd::qif30::AttributesType Attributes_type;
      typedef ::xsd::cxx::tree::optional< Attributes_type > Attributes_optional;
      typedef ::xsd::cxx::tree::traits< Attributes_type, wchar_t > Attributes_traits;

      const Attributes_optional&
      Attributes () const;

      Attributes_optional&
      Attributes ();

      void
      Attributes (const Attributes_type& x);

      void
      Attributes (const Attributes_optional& x);

      void
      Attributes (::std::unique_ptr< Attributes_type > p);

      // VersionHistory
      //
      typedef ::xsd::qif30::VersionHistoryType VersionHistory_type;
      typedef ::xsd::cxx::tree::optional< VersionHistory_type > VersionHistory_optional;
      typedef ::xsd::cxx::tree::traits< VersionHistory_type, wchar_t > VersionHistory_traits;

      const VersionHistory_optional&
      VersionHistory () const;

      VersionHistory_optional&
      VersionHistory ();

      void
      VersionHistory (const VersionHistory_type& x);

      void
      VersionHistory (const VersionHistory_optional& x);

      void
      VersionHistory (::std::unique_ptr< VersionHistory_type > p);

      // Version
      //
      typedef ::xsd::qif30::VersionBaseType Version_type;
      typedef ::xsd::cxx::tree::optional< Version_type > Version_optional;
      typedef ::xsd::cxx::tree::traits< Version_type, wchar_t > Version_traits;

      const Version_optional&
      Version () const;

      Version_optional&
      Version ();

      void
      Version (const Version_type& x);

      void
      Version (const Version_optional& x);

      void
      Version (::std::unique_ptr< Version_type > p);

      // Header
      //
      typedef ::xsd::qif30::QIFDocumentHeaderType Header_type;
      typedef ::xsd::cxx::tree::optional< Header_type > Header_optional;
      typedef ::xsd::cxx::tree::traits< Header_type, wchar_t > Header_traits;

      const Header_optional&
      Header () const;

      Header_optional&
      Header ();

      void
      Header (const Header_type& x);

      void
      Header (const Header_optional& x);

      void
      Header (::std::unique_ptr< Header_type > p);

      // ValidationCounts
      //
      typedef ::xsd::qif30::ValidationCountsType ValidationCounts_type;
      typedef ::xsd::cxx::tree::optional< ValidationCounts_type > ValidationCounts_optional;
      typedef ::xsd::cxx::tree::traits< ValidationCounts_type, wchar_t > ValidationCounts_traits;

      const ValidationCounts_optional&
      ValidationCounts () const;

      ValidationCounts_optional&
      ValidationCounts ();

      void
      ValidationCounts (const ValidationCounts_type& x);

      void
      ValidationCounts (const ValidationCounts_optional& x);

      void
      ValidationCounts (::std::unique_ptr< ValidationCounts_type > p);

      // ProductDataQuality
      //
      typedef ::xsd::qif30::ProductDataQualityType ProductDataQuality_type;
      typedef ::xsd::cxx::tree::optional< ProductDataQuality_type > ProductDataQuality_optional;
      typedef ::xsd::cxx::tree::traits< ProductDataQuality_type, wchar_t > ProductDataQuality_traits;

      const ProductDataQuality_optional&
      ProductDataQuality () const;

      ProductDataQuality_optional&
      ProductDataQuality ();

      void
      ProductDataQuality (const ProductDataQuality_type& x);

      void
      ProductDataQuality (const ProductDataQuality_optional& x);

      void
      ProductDataQuality (::std::unique_ptr< ProductDataQuality_type > p);

      // ExternalQIFReferences
      //
      typedef ::xsd::qif30::ExternalQIFReferencesType ExternalQIFReferences_type;
      typedef ::xsd::cxx::tree::optional< ExternalQIFReferences_type > ExternalQIFReferences_optional;
      typedef ::xsd::cxx::tree::traits< ExternalQIFReferences_type, wchar_t > ExternalQIFReferences_traits;

      const ExternalQIFReferences_optional&
      ExternalQIFReferences () const;

      ExternalQIFReferences_optional&
      ExternalQIFReferences ();

      void
      ExternalQIFReferences (const ExternalQIFReferences_type& x);

      void
      ExternalQIFReferences (const ExternalQIFReferences_optional& x);

      void
      ExternalQIFReferences (::std::unique_ptr< ExternalQIFReferences_type > p);

      // StandardsDefinitions
      //
      typedef ::xsd::qif30::StandardsType StandardsDefinitions_type;
      typedef ::xsd::cxx::tree::optional< StandardsDefinitions_type > StandardsDefinitions_optional;
      typedef ::xsd::cxx::tree::traits< StandardsDefinitions_type, wchar_t > StandardsDefinitions_traits;

      const StandardsDefinitions_optional&
      StandardsDefinitions () const;

      StandardsDefinitions_optional&
      StandardsDefinitions ();

      void
      StandardsDefinitions (const StandardsDefinitions_type& x);

      void
      StandardsDefinitions (const StandardsDefinitions_optional& x);

      void
      StandardsDefinitions (::std::unique_ptr< StandardsDefinitions_type > p);

      // SoftwareDefinitions
      //
      typedef ::xsd::qif30::SoftwaresType SoftwareDefinitions_type;
      typedef ::xsd::cxx::tree::optional< SoftwareDefinitions_type > SoftwareDefinitions_optional;
      typedef ::xsd::cxx::tree::traits< SoftwareDefinitions_type, wchar_t > SoftwareDefinitions_traits;

      const SoftwareDefinitions_optional&
      SoftwareDefinitions () const;

      SoftwareDefinitions_optional&
      SoftwareDefinitions ();

      void
      SoftwareDefinitions (const SoftwareDefinitions_type& x);

      void
      SoftwareDefinitions (const SoftwareDefinitions_optional& x);

      void
      SoftwareDefinitions (::std::unique_ptr< SoftwareDefinitions_type > p);

      // AlgorithmDefinitions
      //
      typedef ::xsd::qif30::AlgorithmsType AlgorithmDefinitions_type;
      typedef ::xsd::cxx::tree::optional< AlgorithmDefinitions_type > AlgorithmDefinitions_optional;
      typedef ::xsd::cxx::tree::traits< AlgorithmDefinitions_type, wchar_t > AlgorithmDefinitions_traits;

      const AlgorithmDefinitions_optional&
      AlgorithmDefinitions () const;

      AlgorithmDefinitions_optional&
      AlgorithmDefinitions ();

      void
      AlgorithmDefinitions (const AlgorithmDefinitions_type& x);

      void
      AlgorithmDefinitions (const AlgorithmDefinitions_optional& x);

      void
      AlgorithmDefinitions (::std::unique_ptr< AlgorithmDefinitions_type > p);

      // PreInspectionTraceability
      //
      typedef ::xsd::qif30::PreInspectionTraceabilityType PreInspectionTraceability_type;
      typedef ::xsd::cxx::tree::optional< PreInspectionTraceability_type > PreInspectionTraceability_optional;
      typedef ::xsd::cxx::tree::traits< PreInspectionTraceability_type, wchar_t > PreInspectionTraceability_traits;

      const PreInspectionTraceability_optional&
      PreInspectionTraceability () const;

      PreInspectionTraceability_optional&
      PreInspectionTraceability ();

      void
      PreInspectionTraceability (const PreInspectionTraceability_type& x);

      void
      PreInspectionTraceability (const PreInspectionTraceability_optional& x);

      void
      PreInspectionTraceability (::std::unique_ptr< PreInspectionTraceability_type > p);

      // FileUnits
      //
      typedef ::xsd::qif30::FileUnitsType FileUnits_type;
      typedef ::xsd::cxx::tree::optional< FileUnits_type > FileUnits_optional;
      typedef ::xsd::cxx::tree::traits< FileUnits_type, wchar_t > FileUnits_traits;

      const FileUnits_optional&
      FileUnits () const;

      FileUnits_optional&
      FileUnits ();

      void
      FileUnits (const FileUnits_type& x);

      void
      FileUnits (const FileUnits_optional& x);

      void
      FileUnits (::std::unique_ptr< FileUnits_type > p);

      // DatumDefinitions
      //
      typedef ::xsd::qif30::DatumDefinitionsType DatumDefinitions_type;
      typedef ::xsd::cxx::tree::optional< DatumDefinitions_type > DatumDefinitions_optional;
      typedef ::xsd::cxx::tree::traits< DatumDefinitions_type, wchar_t > DatumDefinitions_traits;

      const DatumDefinitions_optional&
      DatumDefinitions () const;

      DatumDefinitions_optional&
      DatumDefinitions ();

      void
      DatumDefinitions (const DatumDefinitions_type& x);

      void
      DatumDefinitions (const DatumDefinitions_optional& x);

      void
      DatumDefinitions (::std::unique_ptr< DatumDefinitions_type > p);

      // DatumTargetDefinitions
      //
      typedef ::xsd::qif30::DatumTargetDefinitionsType DatumTargetDefinitions_type;
      typedef ::xsd::cxx::tree::optional< DatumTargetDefinitions_type > DatumTargetDefinitions_optional;
      typedef ::xsd::cxx::tree::traits< DatumTargetDefinitions_type, wchar_t > DatumTargetDefinitions_traits;

      const DatumTargetDefinitions_optional&
      DatumTargetDefinitions () const;

      DatumTargetDefinitions_optional&
      DatumTargetDefinitions ();

      void
      DatumTargetDefinitions (const DatumTargetDefinitions_type& x);

      void
      DatumTargetDefinitions (const DatumTargetDefinitions_optional& x);

      void
      DatumTargetDefinitions (::std::unique_ptr< DatumTargetDefinitions_type > p);

      // Transforms
      //
      typedef ::xsd::qif30::TransformListType Transforms_type;
      typedef ::xsd::cxx::tree::optional< Transforms_type > Transforms_optional;
      typedef ::xsd::cxx::tree::traits< Transforms_type, wchar_t > Transforms_traits;

      const Transforms_optional&
      Transforms () const;

      Transforms_optional&
      Transforms ();

      void
      Transforms (const Transforms_type& x);

      void
      Transforms (const Transforms_optional& x);

      void
      Transforms (::std::unique_ptr< Transforms_type > p);

      // CoordinateSystems
      //
      typedef ::xsd::qif30::CoordinateSystemsType CoordinateSystems_type;
      typedef ::xsd::cxx::tree::optional< CoordinateSystems_type > CoordinateSystems_optional;
      typedef ::xsd::cxx::tree::traits< CoordinateSystems_type, wchar_t > CoordinateSystems_traits;

      const CoordinateSystems_optional&
      CoordinateSystems () const;

      CoordinateSystems_optional&
      CoordinateSystems ();

      void
      CoordinateSystems (const CoordinateSystems_type& x);

      void
      CoordinateSystems (const CoordinateSystems_optional& x);

      void
      CoordinateSystems (::std::unique_ptr< CoordinateSystems_type > p);

      // DatumReferenceFrames
      //
      typedef ::xsd::qif30::DatumReferenceFramesType DatumReferenceFrames_type;
      typedef ::xsd::cxx::tree::optional< DatumReferenceFrames_type > DatumReferenceFrames_optional;
      typedef ::xsd::cxx::tree::traits< DatumReferenceFrames_type, wchar_t > DatumReferenceFrames_traits;

      const DatumReferenceFrames_optional&
      DatumReferenceFrames () const;

      DatumReferenceFrames_optional&
      DatumReferenceFrames ();

      void
      DatumReferenceFrames (const DatumReferenceFrames_type& x);

      void
      DatumReferenceFrames (const DatumReferenceFrames_optional& x);

      void
      DatumReferenceFrames (::std::unique_ptr< DatumReferenceFrames_type > p);

      // MeasurementResources
      //
      typedef ::xsd::qif30::MeasurementResourcesType MeasurementResources_type;
      typedef ::xsd::cxx::tree::optional< MeasurementResources_type > MeasurementResources_optional;
      typedef ::xsd::cxx::tree::traits< MeasurementResources_type, wchar_t > MeasurementResources_traits;

      const MeasurementResources_optional&
      MeasurementResources () const;

      MeasurementResources_optional&
      MeasurementResources ();

      void
      MeasurementResources (const MeasurementResources_type& x);

      void
      MeasurementResources (const MeasurementResources_optional& x);

      void
      MeasurementResources (::std::unique_ptr< MeasurementResources_type > p);

      // ThreadSpecifications
      //
      typedef ::xsd::qif30::ThreadSpecificationsType ThreadSpecifications_type;
      typedef ::xsd::cxx::tree::optional< ThreadSpecifications_type > ThreadSpecifications_optional;
      typedef ::xsd::cxx::tree::traits< ThreadSpecifications_type, wchar_t > ThreadSpecifications_traits;

      const ThreadSpecifications_optional&
      ThreadSpecifications () const;

      ThreadSpecifications_optional&
      ThreadSpecifications ();

      void
      ThreadSpecifications (const ThreadSpecifications_type& x);

      void
      ThreadSpecifications (const ThreadSpecifications_optional& x);

      void
      ThreadSpecifications (::std::unique_ptr< ThreadSpecifications_type > p);

      // Product
      //
      typedef ::xsd::qif30::ProductType Product_type;
      typedef ::xsd::cxx::tree::optional< Product_type > Product_optional;
      typedef ::xsd::cxx::tree::traits< Product_type, wchar_t > Product_traits;

      const Product_optional&
      Product () const;

      Product_optional&
      Product ();

      void
      Product (const Product_type& x);

      void
      Product (const Product_optional& x);

      void
      Product (::std::unique_ptr< Product_type > p);

      // Features
      //
      typedef ::xsd::qif30::FeatureAspectsListsType Features_type;
      typedef ::xsd::cxx::tree::optional< Features_type > Features_optional;
      typedef ::xsd::cxx::tree::traits< Features_type, wchar_t > Features_traits;

      const Features_optional&
      Features () const;

      Features_optional&
      Features ();

      void
      Features (const Features_type& x);

      void
      Features (const Features_optional& x);

      void
      Features (::std::unique_ptr< Features_type > p);

      // FeatureZones
      //
      typedef ::xsd::qif30::FeatureZoneListType FeatureZones_type;
      typedef ::xsd::cxx::tree::optional< FeatureZones_type > FeatureZones_optional;
      typedef ::xsd::cxx::tree::traits< FeatureZones_type, wchar_t > FeatureZones_traits;

      const FeatureZones_optional&
      FeatureZones () const;

      FeatureZones_optional&
      FeatureZones ();

      void
      FeatureZones (const FeatureZones_type& x);

      void
      FeatureZones (const FeatureZones_optional& x);

      void
      FeatureZones (::std::unique_ptr< FeatureZones_type > p);

      // Characteristics
      //
      typedef ::xsd::qif30::CharacteristicAspectsListsType Characteristics_type;
      typedef ::xsd::cxx::tree::optional< Characteristics_type > Characteristics_optional;
      typedef ::xsd::cxx::tree::traits< Characteristics_type, wchar_t > Characteristics_traits;

      const Characteristics_optional&
      Characteristics () const;

      Characteristics_optional&
      Characteristics ();

      void
      Characteristics (const Characteristics_type& x);

      void
      Characteristics (const Characteristics_optional& x);

      void
      Characteristics (::std::unique_ptr< Characteristics_type > p);

      // Plan
      //
      typedef ::xsd::qif30::PlanType Plan_type;
      typedef ::xsd::cxx::tree::optional< Plan_type > Plan_optional;
      typedef ::xsd::cxx::tree::traits< Plan_type, wchar_t > Plan_traits;

      const Plan_optional&
      Plan () const;

      Plan_optional&
      Plan ();

      void
      Plan (const Plan_type& x);

      void
      Plan (const Plan_optional& x);

      void
      Plan (::std::unique_ptr< Plan_type > p);

      // Results
      //
      typedef ::xsd::qif30::ResultsType Results_type;
      typedef ::xsd::cxx::tree::optional< Results_type > Results_optional;
      typedef ::xsd::cxx::tree::traits< Results_type, wchar_t > Results_traits;

      const Results_optional&
      Results () const;

      Results_optional&
      Results ();

      void
      Results (const Results_type& x);

      void
      Results (const Results_optional& x);

      void
      Results (::std::unique_ptr< Results_type > p);

      // Statistics
      //
      typedef ::xsd::qif30::StatisticsType Statistics_type;
      typedef ::xsd::cxx::tree::optional< Statistics_type > Statistics_optional;
      typedef ::xsd::cxx::tree::traits< Statistics_type, wchar_t > Statistics_traits;

      const Statistics_optional&
      Statistics () const;

      Statistics_optional&
      Statistics ();

      void
      Statistics (const Statistics_type& x);

      void
      Statistics (const Statistics_optional& x);

      void
      Statistics (::std::unique_ptr< Statistics_type > p);

      // ManufacturingProcessTraceabilities
      //
      typedef ::xsd::qif30::ManufacturingProcessTraceabilitiesType ManufacturingProcessTraceabilities_type;
      typedef ::xsd::cxx::tree::optional< ManufacturingProcessTraceabilities_type > ManufacturingProcessTraceabilities_optional;
      typedef ::xsd::cxx::tree::traits< ManufacturingProcessTraceabilities_type, wchar_t > ManufacturingProcessTraceabilities_traits;

      const ManufacturingProcessTraceabilities_optional&
      ManufacturingProcessTraceabilities () const;

      ManufacturingProcessTraceabilities_optional&
      ManufacturingProcessTraceabilities ();

      void
      ManufacturingProcessTraceabilities (const ManufacturingProcessTraceabilities_type& x);

      void
      ManufacturingProcessTraceabilities (const ManufacturingProcessTraceabilities_optional& x);

      void
      ManufacturingProcessTraceabilities (::std::unique_ptr< ManufacturingProcessTraceabilities_type > p);

      // Rules
      //
      typedef ::xsd::qif30::QIFRulesType Rules_type;
      typedef ::xsd::cxx::tree::optional< Rules_type > Rules_optional;
      typedef ::xsd::cxx::tree::traits< Rules_type, wchar_t > Rules_traits;

      const Rules_optional&
      Rules () const;

      Rules_optional&
      Rules ();

      void
      Rules (const Rules_type& x);

      void
      Rules (const Rules_optional& x);

      void
      Rules (::std::unique_ptr< Rules_type > p);

      // UserDataXML
      //
      typedef ::xsd::qif30::UserDataXMLType UserDataXML_type;
      typedef ::xsd::cxx::tree::optional< UserDataXML_type > UserDataXML_optional;
      typedef ::xsd::cxx::tree::traits< UserDataXML_type, wchar_t > UserDataXML_traits;

      const UserDataXML_optional&
      UserDataXML () const;

      UserDataXML_optional&
      UserDataXML ();

      void
      UserDataXML (const UserDataXML_type& x);

      void
      UserDataXML (const UserDataXML_optional& x);

      void
      UserDataXML (::std::unique_ptr< UserDataXML_type > p);

      // Signature
      //
      typedef ::xsd::qif30::SignatureType Signature_type;
      typedef ::xsd::cxx::tree::optional< Signature_type > Signature_optional;
      typedef ::xsd::cxx::tree::traits< Signature_type, wchar_t > Signature_traits;

      const Signature_optional&
      Signature () const;

      Signature_optional&
      Signature ();

      void
      Signature (const Signature_type& x);

      void
      Signature (const Signature_optional& x);

      void
      Signature (::std::unique_ptr< Signature_type > p);

      // versionQIF
      //
      typedef ::xml_schema::nmtoken versionQIF_type;
      typedef ::xsd::cxx::tree::traits< versionQIF_type, wchar_t > versionQIF_traits;

      const versionQIF_type&
      versionQIF () const;

      static const versionQIF_type&
      versionQIF_default_value ();

      // idMax
      //
      typedef ::xml_schema::unsigned_int idMax_type;
      typedef ::xsd::cxx::tree::traits< idMax_type, wchar_t > idMax_traits;

      const idMax_type&
      idMax () const;

      idMax_type&
      idMax ();

      void
      idMax (const idMax_type& x);

      // Constructors.
      //
      QIFDocumentType ();

      QIFDocumentType (const QPId_type&,
                       const idMax_type&);

      QIFDocumentType (const xercesc::DOMElement& e,
                       ::xml_schema::flags f = 0,
                       ::xml_schema::container* c = 0);

      QIFDocumentType (const QIFDocumentType& x,
                       ::xml_schema::flags f = 0,
                       ::xml_schema::container* c = 0);

      virtual QIFDocumentType*
      _clone (::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0) const;

      QIFDocumentType&
      operator= (const QIFDocumentType& x);

      virtual 
      ~QIFDocumentType ();

      // Implementation.
      //
      protected:
      void
      parse (::xsd::cxx::xml::dom::parser< wchar_t >&,
             ::xml_schema::flags);

      protected:
      ::xsd::cxx::tree::one< QPId_type > QPId_;
      Attributes_optional Attributes_;
      VersionHistory_optional VersionHistory_;
      Version_optional Version_;
      Header_optional Header_;
      ValidationCounts_optional ValidationCounts_;
      ProductDataQuality_optional ProductDataQuality_;
      ExternalQIFReferences_optional ExternalQIFReferences_;
      StandardsDefinitions_optional StandardsDefinitions_;
      SoftwareDefinitions_optional SoftwareDefinitions_;
      AlgorithmDefinitions_optional AlgorithmDefinitions_;
      PreInspectionTraceability_optional PreInspectionTraceability_;
      FileUnits_optional FileUnits_;
      DatumDefinitions_optional DatumDefinitions_;
      DatumTargetDefinitions_optional DatumTargetDefinitions_;
      Transforms_optional Transforms_;
      CoordinateSystems_optional CoordinateSystems_;
      DatumReferenceFrames_optional DatumReferenceFrames_;
      MeasurementResources_optional MeasurementResources_;
      ThreadSpecifications_optional ThreadSpecifications_;
      Product_optional Product_;
      Features_optional Features_;
      FeatureZones_optional FeatureZones_;
      Characteristics_optional Characteristics_;
      Plan_optional Plan_;
      Results_optional Results_;
      Statistics_optional Statistics_;
      ManufacturingProcessTraceabilities_optional ManufacturingProcessTraceabilities_;
      Rules_optional Rules_;
      UserDataXML_optional UserDataXML_;
      Signature_optional Signature_;
      ::xsd::cxx::tree::one< versionQIF_type > versionQIF_;
      static const versionQIF_type versionQIF_default_value_;
      ::xsd::cxx::tree::one< idMax_type > idMax_;
    };

    class QIF30_SYMBOL_DECL QIFDocumentHeaderType: public ::xml_schema::type
    {
      public:
      // Application
      //
      typedef ::xsd::qif30::ApplicationType Application_type;
      typedef ::xsd::cxx::tree::optional< Application_type > Application_optional;
      typedef ::xsd::cxx::tree::traits< Application_type, wchar_t > Application_traits;

      const Application_optional&
      Application () const;

      Application_optional&
      Application ();

      void
      Application (const Application_type& x);

      void
      Application (const Application_optional& x);

      void
      Application (::std::unique_ptr< Application_type > p);

      // Author
      //
      typedef ::xsd::qif30::AuthorType Author_type;
      typedef ::xsd::cxx::tree::optional< Author_type > Author_optional;
      typedef ::xsd::cxx::tree::traits< Author_type, wchar_t > Author_traits;

      const Author_optional&
      Author () const;

      Author_optional&
      Author ();

      void
      Author (const Author_type& x);

      void
      Author (const Author_optional& x);

      void
      Author (::std::unique_ptr< Author_type > p);

      // ApplicationSource
      //
      typedef ::xsd::qif30::ApplicationType ApplicationSource_type;
      typedef ::xsd::cxx::tree::optional< ApplicationSource_type > ApplicationSource_optional;
      typedef ::xsd::cxx::tree::traits< ApplicationSource_type, wchar_t > ApplicationSource_traits;

      const ApplicationSource_optional&
      ApplicationSource () const;

      ApplicationSource_optional&
      ApplicationSource ();

      void
      ApplicationSource (const ApplicationSource_type& x);

      void
      ApplicationSource (const ApplicationSource_optional& x);

      void
      ApplicationSource (::std::unique_ptr< ApplicationSource_type > p);

      // Description
      //
      typedef ::xml_schema::string Description_type;
      typedef ::xsd::cxx::tree::optional< Description_type > Description_optional;
      typedef ::xsd::cxx::tree::traits< Description_type, wchar_t > Description_traits;

      const Description_optional&
      Description () const;

      Description_optional&
      Description ();

      void
      Description (const Description_type& x);

      void
      Description (const Description_optional& x);

      void
      Description (::std::unique_ptr< Description_type > p);

      // Scope
      //
      typedef ::xml_schema::string Scope_type;
      typedef ::xsd::cxx::tree::optional< Scope_type > Scope_optional;
      typedef ::xsd::cxx::tree::traits< Scope_type, wchar_t > Scope_traits;

      const Scope_optional&
      Scope () const;

      Scope_optional&
      Scope ();

      void
      Scope (const Scope_type& x);

      void
      Scope (const Scope_optional& x);

      void
      Scope (::std::unique_ptr< Scope_type > p);

      // Constructors.
      //
      QIFDocumentHeaderType ();

      QIFDocumentHeaderType (const xercesc::DOMElement& e,
                             ::xml_schema::flags f = 0,
                             ::xml_schema::container* c = 0);

      QIFDocumentHeaderType (const QIFDocumentHeaderType& x,
                             ::xml_schema::flags f = 0,
                             ::xml_schema::container* c = 0);

      virtual QIFDocumentHeaderType*
      _clone (::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0) const;

      QIFDocumentHeaderType&
      operator= (const QIFDocumentHeaderType& x);

      virtual 
      ~QIFDocumentHeaderType ();

      // Implementation.
      //
      protected:
      void
      parse (::xsd::cxx::xml::dom::parser< wchar_t >&,
             ::xml_schema::flags);

      protected:
      Application_optional Application_;
      Author_optional Author_;
      ApplicationSource_optional ApplicationSource_;
      Description_optional Description_;
      Scope_optional Scope_;
    };

    class QIF30_SYMBOL_DECL ExternalQIFReferencesType: public ::xml_schema::type
    {
      public:
      // ExternalQIFDocument
      //
      typedef ::xsd::qif30::ExternalQIFDocumentReferenceType ExternalQIFDocument_type;
      typedef ::xsd::cxx::tree::sequence< ExternalQIFDocument_type > ExternalQIFDocument_sequence;
      typedef xsd::cxx::tree::sequence< ExternalQIFDocument_type >::iterator ExternalQIFDocument_iterator;
      typedef xsd::cxx::tree::sequence< ExternalQIFDocument_type >::const_iterator ExternalQIFDocument_const_iterator;
      typedef ::xsd::cxx::tree::traits< ExternalQIFDocument_type, wchar_t > ExternalQIFDocument_traits;

      const ExternalQIFDocument_sequence&
      ExternalQIFDocument () const;

      ExternalQIFDocument_sequence&
      ExternalQIFDocument ();

      void
      ExternalQIFDocument (const ExternalQIFDocument_sequence& s);

      // n
      //
      typedef ::xsd::qif30::NaturalType n_type;
      typedef ::xsd::cxx::tree::traits< n_type, wchar_t > n_traits;

      const n_type&
      n () const;

      n_type&
      n ();

      void
      n (const n_type& x);

      void
      n (::std::unique_ptr< n_type > p);

      // Constructors.
      //
      ExternalQIFReferencesType ();

      ExternalQIFReferencesType (const n_type&);

      ExternalQIFReferencesType (const xercesc::DOMElement& e,
                                 ::xml_schema::flags f = 0,
                                 ::xml_schema::container* c = 0);

      ExternalQIFReferencesType (const ExternalQIFReferencesType& x,
                                 ::xml_schema::flags f = 0,
                                 ::xml_schema::container* c = 0);

      virtual ExternalQIFReferencesType*
      _clone (::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0) const;

      ExternalQIFReferencesType&
      operator= (const ExternalQIFReferencesType& x);

      virtual 
      ~ExternalQIFReferencesType ();

      // Implementation.
      //
      protected:
      void
      parse (::xsd::cxx::xml::dom::parser< wchar_t >&,
             ::xml_schema::flags);

      protected:
      ExternalQIFDocument_sequence ExternalQIFDocument_;
      ::xsd::cxx::tree::one< n_type > n_;
    };

    class QIF30_SYMBOL_DECL ExternalQIFDocumentReferenceType: public ::xml_schema::type
    {
      public:
      // QPId
      //
      typedef ::xsd::qif30::QPIdReferenceType QPId_type;
      typedef ::xsd::cxx::tree::traits< QPId_type, wchar_t > QPId_traits;

      const QPId_type&
      QPId () const;

      QPId_type&
      QPId ();

      void
      QPId (const QPId_type& x);

      void
      QPId (::std::unique_ptr< QPId_type > p);

      // URI
      //
      typedef ::xml_schema::uri URI_type;
      typedef ::xsd::cxx::tree::optional< URI_type > URI_optional;
      typedef ::xsd::cxx::tree::traits< URI_type, wchar_t > URI_traits;

      const URI_optional&
      URI () const;

      URI_optional&
      URI ();

      void
      URI (const URI_type& x);

      void
      URI (const URI_optional& x);

      void
      URI (::std::unique_ptr< URI_type > p);

      // Description
      //
      typedef ::xml_schema::string Description_type;
      typedef ::xsd::cxx::tree::optional< Description_type > Description_optional;
      typedef ::xsd::cxx::tree::traits< Description_type, wchar_t > Description_traits;

      const Description_optional&
      Description () const;

      Description_optional&
      Description ();

      void
      Description (const Description_type& x);

      void
      Description (const Description_optional& x);

      void
      Description (::std::unique_ptr< Description_type > p);

      // id
      //
      typedef ::xsd::qif30::QIFIdType id_type;
      typedef ::xsd::cxx::tree::traits< id_type, wchar_t > id_traits;

      const id_type&
      id () const;

      id_type&
      id ();

      void
      id (const id_type& x);

      void
      id (::std::unique_ptr< id_type > p);

      // Constructors.
      //
      ExternalQIFDocumentReferenceType ();

      ExternalQIFDocumentReferenceType (const QPId_type&,
                                        const id_type&);

      ExternalQIFDocumentReferenceType (const xercesc::DOMElement& e,
                                        ::xml_schema::flags f = 0,
                                        ::xml_schema::container* c = 0);

      ExternalQIFDocumentReferenceType (const ExternalQIFDocumentReferenceType& x,
                                        ::xml_schema::flags f = 0,
                                        ::xml_schema::container* c = 0);

      virtual ExternalQIFDocumentReferenceType*
      _clone (::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0) const;

      ExternalQIFDocumentReferenceType&
      operator= (const ExternalQIFDocumentReferenceType& x);

      virtual 
      ~ExternalQIFDocumentReferenceType ();

      // Implementation.
      //
      protected:
      void
      parse (::xsd::cxx::xml::dom::parser< wchar_t >&,
             ::xml_schema::flags);

      protected:
      ::xsd::cxx::tree::one< QPId_type > QPId_;
      URI_optional URI_;
      Description_optional Description_;
      ::xsd::cxx::tree::one< id_type > id_;
    };
  }
}

#include <iosfwd>

#include <xercesc/sax/InputSource.hpp>
#include <xercesc/dom/DOMDocument.hpp>
#include <xercesc/dom/DOMErrorHandler.hpp>

namespace xsd
{
  namespace qif30
  {
    // Parse a URI or a local file.
    //

    QIF30_SYMBOL_DECL
    ::std::unique_ptr< ::xsd::qif30::QIFDocumentType >
    QIFDocument (const ::std::wstring& uri,
                 ::xml_schema::flags f = 0,
                 const ::xml_schema::properties& p = ::xml_schema::properties ());

    QIF30_SYMBOL_DECL
    ::std::unique_ptr< ::xsd::qif30::QIFDocumentType >
    QIFDocument (const ::std::wstring& uri,
                 ::xml_schema::error_handler& eh,
                 ::xml_schema::flags f = 0,
                 const ::xml_schema::properties& p = ::xml_schema::properties ());

    QIF30_SYMBOL_DECL
    ::std::unique_ptr< ::xsd::qif30::QIFDocumentType >
    QIFDocument (const ::std::wstring& uri,
                 xercesc::DOMErrorHandler& eh,
                 ::xml_schema::flags f = 0,
                 const ::xml_schema::properties& p = ::xml_schema::properties ());

    // Parse std::istream.
    //

    QIF30_SYMBOL_DECL
    ::std::unique_ptr< ::xsd::qif30::QIFDocumentType >
    QIFDocument (::std::istream& is,
                 ::xml_schema::flags f = 0,
                 const ::xml_schema::properties& p = ::xml_schema::properties ());

    QIF30_SYMBOL_DECL
    ::std::unique_ptr< ::xsd::qif30::QIFDocumentType >
    QIFDocument (::std::istream& is,
                 ::xml_schema::error_handler& eh,
                 ::xml_schema::flags f = 0,
                 const ::xml_schema::properties& p = ::xml_schema::properties ());

    QIF30_SYMBOL_DECL
    ::std::unique_ptr< ::xsd::qif30::QIFDocumentType >
    QIFDocument (::std::istream& is,
                 xercesc::DOMErrorHandler& eh,
                 ::xml_schema::flags f = 0,
                 const ::xml_schema::properties& p = ::xml_schema::properties ());

    QIF30_SYMBOL_DECL
    ::std::unique_ptr< ::xsd::qif30::QIFDocumentType >
    QIFDocument (::std::istream& is,
                 const ::std::wstring& id,
                 ::xml_schema::flags f = 0,
                 const ::xml_schema::properties& p = ::xml_schema::properties ());

    QIF30_SYMBOL_DECL
    ::std::unique_ptr< ::xsd::qif30::QIFDocumentType >
    QIFDocument (::std::istream& is,
                 const ::std::wstring& id,
                 ::xml_schema::error_handler& eh,
                 ::xml_schema::flags f = 0,
                 const ::xml_schema::properties& p = ::xml_schema::properties ());

    QIF30_SYMBOL_DECL
    ::std::unique_ptr< ::xsd::qif30::QIFDocumentType >
    QIFDocument (::std::istream& is,
                 const ::std::wstring& id,
                 xercesc::DOMErrorHandler& eh,
                 ::xml_schema::flags f = 0,
                 const ::xml_schema::properties& p = ::xml_schema::properties ());

    // Parse xercesc::InputSource.
    //

    QIF30_SYMBOL_DECL
    ::std::unique_ptr< ::xsd::qif30::QIFDocumentType >
    QIFDocument (xercesc::InputSource& is,
                 ::xml_schema::flags f = 0,
                 const ::xml_schema::properties& p = ::xml_schema::properties ());

    QIF30_SYMBOL_DECL
    ::std::unique_ptr< ::xsd::qif30::QIFDocumentType >
    QIFDocument (xercesc::InputSource& is,
                 ::xml_schema::error_handler& eh,
                 ::xml_schema::flags f = 0,
                 const ::xml_schema::properties& p = ::xml_schema::properties ());

    QIF30_SYMBOL_DECL
    ::std::unique_ptr< ::xsd::qif30::QIFDocumentType >
    QIFDocument (xercesc::InputSource& is,
                 xercesc::DOMErrorHandler& eh,
                 ::xml_schema::flags f = 0,
                 const ::xml_schema::properties& p = ::xml_schema::properties ());

    // Parse xercesc::DOMDocument.
    //

    QIF30_SYMBOL_DECL
    ::std::unique_ptr< ::xsd::qif30::QIFDocumentType >
    QIFDocument (const xercesc::DOMDocument& d,
                 ::xml_schema::flags f = 0,
                 const ::xml_schema::properties& p = ::xml_schema::properties ());

    QIF30_SYMBOL_DECL
    ::std::unique_ptr< ::xsd::qif30::QIFDocumentType >
    QIFDocument (::xml_schema::dom::unique_ptr< xercesc::DOMDocument > d,
                 ::xml_schema::flags f = 0,
                 const ::xml_schema::properties& p = ::xml_schema::properties ());
  }
}

#include <iosfwd>

#include <xercesc/dom/DOMDocument.hpp>
#include <xercesc/dom/DOMErrorHandler.hpp>
#include <xercesc/framework/XMLFormatter.hpp>

#include <xsd/cxx/xml/dom/auto-ptr.hxx>

namespace xsd
{
  namespace qif30
  {
    // Serialize to std::ostream.
    //

    QIF30_SYMBOL_DECL
    void
    QIFDocument (::std::ostream& os,
                 const ::xsd::qif30::QIFDocumentType& x, 
                 const ::xml_schema::namespace_infomap& m = ::xml_schema::namespace_infomap (),
                 const ::std::wstring& e = L"UTF-8",
                 ::xml_schema::flags f = 0);

    QIF30_SYMBOL_DECL
    void
    QIFDocument (::std::ostream& os,
                 const ::xsd::qif30::QIFDocumentType& x, 
                 ::xml_schema::error_handler& eh,
                 const ::xml_schema::namespace_infomap& m = ::xml_schema::namespace_infomap (),
                 const ::std::wstring& e = L"UTF-8",
                 ::xml_schema::flags f = 0);

    QIF30_SYMBOL_DECL
    void
    QIFDocument (::std::ostream& os,
                 const ::xsd::qif30::QIFDocumentType& x, 
                 xercesc::DOMErrorHandler& eh,
                 const ::xml_schema::namespace_infomap& m = ::xml_schema::namespace_infomap (),
                 const ::std::wstring& e = L"UTF-8",
                 ::xml_schema::flags f = 0);

    // Serialize to xercesc::XMLFormatTarget.
    //

    QIF30_SYMBOL_DECL
    void
    QIFDocument (xercesc::XMLFormatTarget& ft,
                 const ::xsd::qif30::QIFDocumentType& x, 
                 const ::xml_schema::namespace_infomap& m = ::xml_schema::namespace_infomap (),
                 const ::std::wstring& e = L"UTF-8",
                 ::xml_schema::flags f = 0);

    QIF30_SYMBOL_DECL
    void
    QIFDocument (xercesc::XMLFormatTarget& ft,
                 const ::xsd::qif30::QIFDocumentType& x, 
                 ::xml_schema::error_handler& eh,
                 const ::xml_schema::namespace_infomap& m = ::xml_schema::namespace_infomap (),
                 const ::std::wstring& e = L"UTF-8",
                 ::xml_schema::flags f = 0);

    QIF30_SYMBOL_DECL
    void
    QIFDocument (xercesc::XMLFormatTarget& ft,
                 const ::xsd::qif30::QIFDocumentType& x, 
                 xercesc::DOMErrorHandler& eh,
                 const ::xml_schema::namespace_infomap& m = ::xml_schema::namespace_infomap (),
                 const ::std::wstring& e = L"UTF-8",
                 ::xml_schema::flags f = 0);

    // Serialize to an existing xercesc::DOMDocument.
    //

    QIF30_SYMBOL_DECL
    void
    QIFDocument (xercesc::DOMDocument& d,
                 const ::xsd::qif30::QIFDocumentType& x,
                 ::xml_schema::flags f = 0);

    // Serialize to a new xercesc::DOMDocument.
    //

    QIF30_SYMBOL_DECL
    ::xml_schema::dom::unique_ptr< xercesc::DOMDocument >
    QIFDocument (const ::xsd::qif30::QIFDocumentType& x, 
                 const ::xml_schema::namespace_infomap& m = ::xml_schema::namespace_infomap (),
                 ::xml_schema::flags f = 0);

    QIF30_SYMBOL_DECL
    void
    operator<< (xercesc::DOMElement&, const QIFDocumentType&);

    QIF30_SYMBOL_DECL
    void
    operator<< (xercesc::DOMElement&, const QIFDocumentHeaderType&);

    QIF30_SYMBOL_DECL
    void
    operator<< (xercesc::DOMElement&, const ExternalQIFReferencesType&);

    QIF30_SYMBOL_DECL
    void
    operator<< (xercesc::DOMElement&, const ExternalQIFDocumentReferenceType&);
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

#endif // CXX___QIFAPPLICATIONS_QIFDOCUMENT_HXX
